### ISSUE TITLE
ncm-grub: drop non-multiboot support

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#1000]
As part of #999, we could consider dropping support for grubby versions that do not support multiboot.

It would simplify the code a bit and remove a grub2-incompatible codepath.

On centos 5.11/6.5 and 7.2, grubby has multiboot support.

**Comment by stdweird** [comment]
@ned21 @ajf8 does grubby have multiboot support on the oldest OS you want ncm-grub to work with?

**Comment by ned21** [comment]
I believe we are tracking 5.11 which has:

$ rpm -qf /sbin/grubby
mkinitrd-5.1.19.6-82.el5

Does that answer the question?

**Comment by stdweird** [comment]
easiest way to check is to run
```
grubby --help |grep multiboot
```
returns anything related to `multiboot` or `mbargs` (it's more or less also what the code does).

**Comment by ned21** [comment]
```
grubby --help | grep multiboot
  --add-multiboot=STRING          add an entry for the specified multiboot
  --mbargs=STRING                 default arguments for the new multiboot
                                  kernel or new arguments for multiboot kernel
  --remove-mbargs=STRING          remove multiboot kernel arguments
  --remove-multiboot=STRING       remove all entries for the specified
                                  multiboot kernel
```

**Comment by stdweird** [comment]
yep, that version also has it.
if you have by any chance access to older el5 or el4 boxes, it could be useful to know if this existed in older el5 releases. i think it is an el4 leftover when grub was still new and fancy.

**Comment by stdweird** [comment]
Fixed in https://github.com/quattor/configuration-modules-core/pull/999/commits/2804d1a9e2783a34a14134b2145295ad8e81c2a2
