### ISSUE TITLE
ncm-interactivelimits: errors on 16.12 due to Perl warning

### ISSUE THREAD

**Issue by ned21** [quattor/configuration-modules-core#1007]
```
# rpm -q ncm-interactivelimits ccm ncm-ncd
ncm-interactivelimits-16.10.0-1.noarch
ccm-16.10.0-1.noarch
ncm-ncd-16.10.0-1.noarch
```

[VERB] File /var/run/quattor-components/interactivelimits was modified
[VERB] state for component interactivelimits /var/run/quattor-components/interactivelimits changed.
[VERB] Perl warning: Subroutine unescape redefined at /usr/lib/perl/NCM/Component.pm line 138.

[DEBUG] Changed to /tmp before executing component interactivelimits method Configure
[INFO] configure on component interactivelimits executed, 0 errors, 0 warnings

In 16.12, warnings have been upgraded to errors so the component now fails.

```
# grep unescape /usr/lib/perl/NCM/Component/interactivelimits.pm
#
```

so I am unclear on what bit of code in interactivelimits is actually triggering this.

**Comment by stdweird** [comment]
is `ncm-ncd` up-to-date? and can you share `--debug 5` outpput? (or pm it)

the warning should have been fixed with https://github.com/quattor/ncm-ncd/commit/529e64c558136d1ff824f81bc9f62c5f194ce8f4

and what do you mean with `warnings are errors`?

**Comment by ned21** [comment]
False alarm caused by some package mismatches. Running 100% 16.12 works fine.
