### ISSUE TITLE
ncm-aiiserver: manage the new config options introduced for UEFI support

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#1050]
https://github.com/quattor/aii/pull/225 added UEFI support to AII and introduced new configuration options in the `aii-shellfe` configuration file. `ncm-aiiserver` (or its replacement) should allow to manage them (even though in most cases, no new config option is needed for the UEFI support).

**Comment by stdweird** [comment]
@jouvin duplicate of #960?

**Comment by jouvin** [comment]
Sorry I missed that I already opened an issue a while ago!
