### ISSUE TITLE
ncm-network: /dev/enp4s0f0 and /dev/enp4s0f1 cannot be configured

### ISSUE THREAD

**Issue by nowack73** [quattor/configuration-modules-core#1069]
The regular expressions in network.pm (version 17.2) does not allow to configure /dev/enp4s0f0 and /dev/enp4s0f1. (This naming convention is used in SL7 for "Emulex Corporation OneConnect 10Gb NIC", in SL6 it was eth*) 

Chaning line 280 from
```
    my $dev_regexp='-((eth|seth|em|bond|br|ovirtmgmt|vlan|usb|ib|p\d+p|en(o|(p\d+)?s))\d+|enx[[:xdigit:]]{12})(\.\d+)?';
```
to
```
    my $dev_regexp='-((eth|seth|em|bond|br|ovirtmgmt|vlan|usb|ib|p\d+p|en(o|(p\d+)?s))\d+|enx[[:xdigit:]]{12})(.\d+)?';
```
fixes my problem.

Without this change the name is truncated (leading to enp4s0) and configuration fails.

**Comment by stdweird** [comment]
ah, VIF support. this is not the fix we will implement, as it drops vlan support i think
should be easy nonetheless

**Comment by gombasg** [comment]
I wonder if it would be time to drop any verification/dependency on interface names. The fact is, you can name any interface anyway you like:

```
# ip link add name eth5.8 type dummy
# ip link show eth5.8
6: eth5.8: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether be:7b:2c:a3:17:a6 brd ff:ff:ff:ff:ff:ff
```

**Comment by stdweird** [comment]
@gombasg ncm-network is only concerned about ifcfg files. i don't mind dropping the regexp, but then we need another way to detect devices that are not supported by ncm-network.

**Comment by gombasg** [comment]
@stdweird Well, not just ifcfg-*, but also route-* and rule-* files would match the current pattern. But matching on those prefixes instead would still be a lot simpler than the current suffix match, and the prefixes would change much less often. Another option is to just read the ifcfg-* files - if TYPE/DEVICETYPE/etc. is recognized, then we've found a valid interface name, and we can look for any related files ending with the same name.
