### ISSUE TITLE
ncm-network: Static IPv6 routes are not handled correctly

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#1081]
The schema permits them to be added, but they are not handled correctly by the code.

They should be written to `/etc/sysconfig/network-scripts/route6-INTERFACE` in the format:
```
IP/LENGTH via GATEWAY_IP
```
e.g.
```
2001:DB8::/32 via 2001:DB8:dead:beef::42
```

**Comment by stdweird** [comment]
so in the profile, you would add/mix ipv6 routes with the ipv4 ones? or do you want a separate ipv6_routes entry in the schema?

**Comment by jrha** [comment]
At present the schema allows for them to be mixed, I see no problem with that as long as the code handles them correctly.

**Comment by stdweird** [comment]
@jrha the current schema for a single route has no mandatory attributes; and the code only sets `255.255.255.255` as default netmask.
i'll also add `prefix` attribute (for what is `LENGTH` in your example) and `command` for any arbitrary route command to the schema.
 
it also seems this syntax is valid for ipv4 (even in el5). i'll try to do a safe replacement to this new syntax (ie same config doesn't lead to restart).

and to top it off, for the same effort, i can add support for `ifcfg-rule` and `ifcfg-rule6`.
