### ISSUE TITLE
ncm-network: Allow extra routing options for the default route

### ISSUE THREAD

**Issue by ned21** [quattor/configuration-modules-core#1082]
For rto_min and similar can be handled via a custom /etc/sysconfig/network-scripts/route-eth0.  However you can only add new route entries using /etc/sysconfig/network-scripts/route-eth0, modifying existing entries (including the default route) is not possible. 

Setting `DEFROUTE=no` in `/etc/sysconfig/network-scripts/ifcfg-eth0` prevents the default route being added which allows you to set a custom default route in `/etc/sysconfig/network-scripts/route-eth0 `(including with rto_min)

- [ ] Modify `structure_interface` in `aquilon/components/network/core-schema.tpl`  to accept ```defroute=yes|no```
- [ ] update ncm-network to add DEFROUTE setting to ifcfg-ethX

**Comment by stdweird** [comment]
sounds trivial, but i'd rather add new features to the rewrite

**Comment by stdweird** [comment]
also, to whomever adds this, there's also a `IPV6_DEFROUTE=yes|no` option; should also be added

**Comment by ned21** [comment]
@stdweird No concrete plans to implement this on our end, just logging it for review by others consideration as part of the rewrite.
