### ISSUE TITLE
warnings due to deprecated CCM modules

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#1083]
harmless but annoying; only reported once
```
[WARN] Warning during loading of package NCM::Component::metaconfig: Direct usage of EDG::WP4::CCM::Element is deprecated and contains no functional code besides a limited number of reexported functions and constants from other modules. at /usr/lib/perl/EDG/WP4/CCM/Element.pm line 35.
```

**Comment by jrha** [comment]
Any plans to fix this?

**Comment by stdweird** [comment]
sure, during a rc, simplest form it's search and replace on the whole repo.
`use EDG::WP4::CCM::Element` -> `use EDG::WP4::CCM::Path 16.8.0`
and maybe some components do other odd things with Element, but should only a few. in fact, most component have Element included, but do not use escape or unescape at all, so it can be removed there.
