### ISSUE TITLE
ncm-systemd: Manual intervention required in order for drop-in unit files to have any affect

### ISSUE THREAD

**Issue by alahiff** [quattor/configuration-modules-core#1095]
If you add a drop-in unit file using ncm-systemd, e.g.
```
include 'components/systemd/config';
'/software/components/systemd/unit/{nrpe.service}/file' = dict(
    'only', true,
    'config', dict(
        'service', dict(
            'User', 'nagios',
            'Group', 'nagios',
        ),
    ),
);
```
you need to manually restart the service in order for this to take affect. Is there any way this can be automated? (besides using ncm-filecopy with `restart` instead of ncm-systemd).

**Comment by alahiff** [comment]
Does this change also mean that if you write a complete unit file using ncm-systemd, then update it, the service will be updated as appropriate? (i.e. "systemctl daemon-reload" run and the service restarted). At the moment this doesn't happen, which means that after making changes you need to manually restart services on hosts, which isn't good.

**Comment by stdweird** [comment]
@alahiff it should. i'll look into it.

**Comment by stdweird** [comment]
@alahiff hmmm, did you configure the unit to get started (either via chkconfig or systemd)
can you share the log of a failed run?

**Comment by stdweird** [comment]
@alahiff if you write a unit that is a new service, you have to remove the `only = true` from the configuration.

i used your example data from above, i get entry in log below; and it looks like it worked
```
[VERB] No contents from missing /etc/systemd/system/nrpe.service.d/quattor.conf
[VERB] No original content for /etc/systemd/system/nrpe.service.d/quattor.conf; new content is the diff
[VERB] Changes to /etc/systemd/system/nrpe.service.d/quattor.conf:
[Service]
Group=nagios
User=nagios


[VERB] File /etc/systemd/system/nrpe.service.d/quattor.conf was modified
[VERB] Getting output of command: /usr/bin/systemctl daemon-reload
[VERB] Going to issue conditional restart for nrpe.service due to changed unitfile
[INFO] Only unitfile configuration for unit nrpe.service (state enabled startstop 1 type service shortname nrpe targets multi-user.target possible_missing 0)
```

**Comment by jrha** [comment]
@alahiff can you confirm whether this worked for you?

**Comment by jrha** [comment]
@stdweird I've been testing this on a VM with @alahiff's setup, and it doesn't seem to reloading services.

Here's the config:

```sh
# ccm /software/components/chkconfig/service/etcd/
+-/software/components/chkconfig/service/etcd
  $ on : ''
  $ startstop : true

# ccm /software/components/systemd/unit/etcd_2eservice/
+-/software/components/systemd/unit/etcd_2eservice
  +-file
    +-config
      +-install
        +-WantedBy
          $ 0 : 'multi-user.target'
      +-service
        $ ExecStart : '/usr/bin/etcd --config-file /etc/etcd.conf.yml'
        $ Group : 'etcd'
        $ KillMode : 'process'
        $ LimitNOFILE : 40001
        $ NotifyAccess : 'all'
        $ Restart : 'always'
        $ RestartSec : 10
        $ Type : 'notify'
        $ User : 'etcd'
      +-unit
        +-After
          $ 0 : 'basic.target'
          $ 1 : 'network.target'
        $ Description : 'Etcd distributed key-value store'
        +-Requires
          $ 0 : 'network.target'
    $ replace : true
  $ startstop : true
  $ state : 'enabled'
  +-targets
    $ 0 : 'multi-user'
  $ type : 'service'
```

Here's the relevant part of the debug log (let me know if you want more):
```
[DEBUG] Using Template::Toolkit to render module unitfile
[DEBUG] Contents is a Element instance
[DEBUG] We must ensure that all templates lie below /usr/share/templates/quattor.
[VERB] Using template systemd/unitfile.tt for module unitfile
[VERB] Opening file /etc/systemd/system/etcd.service
[DEBUG] Reading initial contents from /etc/systemd/system/etcd.service
[VERB] Changes to /etc/systemd/system/etcd.service:
@@ -2,10 +2,10 @@
 WantedBy=multi-user.target
 
 [Service]
-ExecStart=/usr/bin/etcd --config-file /etc/etcd.conf.yml --proxy off
+ExecStart=/usr/bin/etcd --config-file /etc/etcd.conf.yml
 Group=etcd
 KillMode=process
-LimitNOFILE=40004
+LimitNOFILE=40001
 NotifyAccess=all
 Restart=always
 RestartSec=10

[VERB] File /etc/systemd/system/etcd.service was modified
[VERB] Getting output of command: /usr/bin/systemctl daemon-reload
[VERB] Add unit name etcd.service (unit etcd_2eservice)
[DEBUG] Add unit etcd.service (state enabled startstop 1 type service shortname etcd targets multi-user.target possible_missing 0)
```

**Comment by stdweird** [comment]
hmmm, the code is https://github.com/quattor/configuration-modules-core/blob/master/ncm-systemd/src/main/perl/Systemd/Service/Unit.pm#L440
can you verify this is latest master? what is the version of /usr/lib/perl/NCM/Component/Systemd/Service/Unit.pm?

it should have added the service to the tryrestart array. 
can you add to https://github.com/quattor/configuration-modules-core/blob/master/ncm-systemd/src/main/perl/Systemd/Service/Unit.pm#L456 the `@tryrestart` in the verbose message strings (by default, it convert it to a space joined string)

**Comment by jrha** [comment]
Ahahaha, test VM was not using code from `master`, apologies, yes it works correctly.
