### ISSUE TITLE
ncm-filecopy: subclassing does not work correctly

### ISSUE THREAD

**Issue by drossy** [quattor/configuration-modules-core#1098]
I needed a filecopy that copied in a script to run that accessed a file via an nfs mount (Commercial software install). Not wanting to change filecopy's pre dependencies for all the other filecopy'd files, I attempted to subclass filecopy:

```
bind '/software/components/latefilecopy' = component_filecopy;
'/software/components/latefilecopy/ncm-module' = 'filecopy';
'/software/components/latefilecopy/dependencies/pre' = list('spma', 'network', 'authconfig', 'autofs');
```

While that all happily compiles, when the latefilecopy component runs, it appears to use the entries configured under filecopy's services entry, not those under latefilecopy's. Is there a hardcoded path in filecopy?

**Comment by stdweird** [comment]
@drossy seems so: https://github.com/quattor/configuration-modules-core/blob/master/ncm-filecopy/src/main/perl/filecopy.pm#L31

that is legacy code, should be replaced with
```perl
my $confighash = $config->getTree($self->prefix());
```
can you give that a try?

**Comment by drossy** [comment]
@stdweird Yup, that works 👍 

Now I guess I need to filecopy a diff in, to patch filecopy.

**Comment by stdweird** [comment]
make a pull request, jenkins will make you an rpm 😄
