### ISSUE TITLE
ncm-gmond: configuration options missing from schema

### ISSUE THREAD

**Issue by drossy** [quattor/configuration-modules-core#1116]
The options max_udp_msg_len, allow_extra_data and host_tmax are missing from the schema for the global section, also bind_hostname is missing from the schema for the udp_send_channel section, when trying to convert our ganglia 3.7 configuration into aquilon.

**Comment by stdweird** [comment]
@drossy can you point me to a manpage where the `max_udp_msg_len` is described? i can't find it https://github.com/ganglia/monitor-core/blob/master/gmond/conf.pod

**Comment by drossy** [comment]
@stdweird It seems to be a hidden option - its mentioned in a config file on https://github.com/ganglia/monitor-core/wiki/Ganglia-Quick-Start and its certainly accepted as a valid option in the config file - I added an invalid option and gmond refused to start, but it happily accepts max_udp_msg_len

**Comment by stdweird** [comment]
i tried to look for it in the coe, but could find it. anyway, what type is it? probably `long(0..)`?

**Comment by jrha** [comment]
https://github.com/ganglia/monitor-core/blob/73488d8af0383fed8b356a6ddf03164adc034463/gmond/gmond.c#L353

**Comment by stdweird** [comment]
added the max_udp_msg_len opitipon as well. feel free to grab rpm from jenkins and try or wait for release
