### ISSUE TITLE
ncm-authconfig: Attempts to restart nscd even if it does not exist

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#1121]
Affects every version including 17.3.0-rc1.

The [`restart_nscd()`](https://github.com/quattor/configuration-modules-core/blob/6efc46cc123bea5f865bc3746645d404869af65d/ncm-authconfig/src/main/perl/authconfig.pm#L461) function does not check if the service it is trying to restart even exists, when it doesn't the following log file pollution occurs and scares users. It is possible that this should actually be solved in `CAF::Service`, discuss.

```
[INFO] authconfig command ERROR produced:
error reading information on service nscd: No such file or directory
error reading information on service nscd: No such file or directory
nscd: unrecognized service
```

**Comment by stdweird** [comment]
see https://github.com/quattor/configuration-modules-core/blob/master/ncm-authconfig/src/main/pan/components/authconfig/schema.pan#L248
if you do not use `nscd`, set `usecache` to false. if usecache is true, and nscd is missing, it should certainly provide an error of some sort.

(you can use `components/authconfig/site-config` to disable it, see from https://github.com/quattor/maven-tools/blob/master/build-profile/pom.xml#L71)

**Comment by jrha** [comment]
Ok thanks, requires some thought, we use nscd in some places but not others.
