### ISSUE TITLE
ncm-authconfig: What is startstop supposed to do?

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#1143]
Ever since the [dawn of time](../commit/34ac980314f286ced6c2ba669e0e8a304c683c87), `ncm-authconfig` has had an option called `startstop`, which is undocumented and in fact seems to have never been referred to in the code.

Is it just an artefact of copy-paste from `ncm-chkconfig` perhaps?

**Comment by stdweird** [comment]
never heard of it. i propose to start deprecating it and schedule it for removal.
