### ISSUE TITLE
ncm-cups: Nodetype of client should stop running cups daemon

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#1189]
_From @quattor-releaser on October 1, 2009 13:59_

Dears,

When using the ncm-cups component to a quattor template, if we define `"/software/components/cups/nodetype" = "client"`
then ncm-cups component does not stop running cups daemon. It should be the case, isn't it ?
Here's a fix:

``` diff
419a420,423
>         else {
>             # Be sure that the server is stopped if it is not enabled
>             $self->serviceControl($services{server},"stop")
>         }
```

the patch is based on:
http://quattor.svn.sourceforge.net/viewvc/quattor/trunk/ncm-components/core/ncm-cups/cups.pm.cin?revision=540

Reported by: Pansanel

_Copied from original issue: quattor/release#197_

**Comment by stdweird** [comment]
you can try to stop it there, but to be sure, you have to disable it via ncm-chkconfig / ncm-systemd

**Comment by jrha** [comment]
Indeed so.
