### ISSUE TITLE
ncm-spma: yum: Support for include

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#1208]
In order to cope with "special" environments (e.g. RHEL) it would be really nice to be able to `include` extra configuration in `yum.conf`, simply adding this to the schema is not enough, as due to vagaries of yum's config parser, the `include` line must be the last line in the file (spma yum is using `FileEditor`). Otherwise yum will ignore subsequent lines of config.

**Comment by drossy** [comment]
Specifically, if the included file has a repo section, then any lines that follow the include statement will be ignored (or maybe considered part of the repo section?) as the include statement is simply replaced with the contents of the file included.

**Comment by jrha** [comment]
This may very soon stop being an issue, but will review in the next release cycle.

**Comment by jrha** [comment]
We no longer need this functionality, so closing this issue.
