### ISSUE TITLE
ncm-cron: Remove support for magic AUTO minutes field

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#1227]
The `smear` property of the `timing` structure provides much better functionality.

Before this can be accomplished we will need to ensure we are not shipping code in the template libraries that makes use of it, unfortunately this currently includes the following:

* template-library-core
  * master
    * `quattor/server/yum_repos.pan`

* template-library-grid
  * umd-3
    * `features/accounting/apel/client.pan`
    * `features/accounting/apel/parser_blah.pan`
    * `features/accounting/apel/parser_condor.pan`
    * `features/accounting/apel/parser_pbs.pan`
    * `features/mkgridmap/lcgdm.pan`
    * `features/wms/crons.pan`
    * `personality/se_dpm/puppet/info_user_proxy.pan`
    * `personality/se_dpm/server/info_user_proxy.pan`
    * `personality/vobox/config.pan`

  * umd-4
    * `features/accounting/apel/client.pan`
    * `features/accounting/apel/parser_blah.pan`
    * `features/accounting/apel/parser_condor.pan`
    * `features/accounting/apel/parser_pbs.pan`
    * `features/mkgridmap/lcgdm.pan`
    * `features/wms/crons.pan`
    * `personality/se_dpm/puppet/info_user_proxy.pan`
    * `personality/se_dpm/server/info_user_proxy.pan`
    
* template-library-standard
  * master
    * `features/fetch-crl/config.pan`

**Comment by ned21** [comment]
I think there's a use case where you can't use smear. ISTR smear only works if the you have a specific hour, so AUTO is useful for when you want to do something like this:

```
AUTO */4 * * * /bin/true
```

If you try to do that with smear it will error in the Perl code.

**Comment by jrha** [comment]
Fair point, I've not got too much experience with using these in anger. We tend to shy away from things that generate values at runtime, for use-cases like this we often use a modulus of the IP address at build time.

e.g.

```pan
'minute' = to_long(replace('[^0-9]', '', PRIMARY_IP)) % 60;
```

**Comment by ned21** [comment]
@jrha - since there is a valid use case for AUTO can we close this, or do you want it to be an enhancement to improve smear to support this?

**Comment by jouvin** [comment]
@jrha is your concern more than avoiding people doing both way of configuring things at the same time? May be we can ensure this by a validation function in the schema...

**Comment by stdweird** [comment]
@jrha will open a new issue and close this one
