### ISSUE TITLE
ncm-ssh: config option renamed between RHEL6 and RHEL7

### ISSUE THREAD

**Issue by drossy** [quattor/configuration-modules-core#1237]
The config option in RHEL6 (OpenSSH_5.3p1) AuthorizedKeysCommandRunAs has been renamed in RHEL7 (OpenSSH_7.4p1) to AuthorizedKeysCommandUser. 

With the AuthorizedKeysCommand option set, sshd fails to start/ncm rolls back as it needs AuthorizedKeysCommandUser to also be set.

**Comment by jrha** [comment]
@drossy is that also true of `AuthorizedKeysCommand` and `AuthorizedKeysCommandRunAs` in openssh 5.3?

**Comment by jrha** [comment]
Answered my own question: `AuthorizedKeysCommandRunAs` was not mandatory in 5.3 if `AuthorizedKeysCommand` was specified. So the name and the behaviour changed.
