### ISSUE TITLE
ncm-systemd: ExecStart should be a list of string, not a string

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#1262]
`ExecStart` can appear multiple times in a unit file to execute several commands. Because of this, if you want to redefine the standard `ExecStart` attribute in a custom file (appearing in a `service.d` directory), you need to first reset the standard `ExecStart` and then define the new one, meaning you need to specifiy at least 2 values. This is not possible with the current schema, as of 17.12. The possibility to have several commands separated by a `;` doesn't apply to the reset case (an empty string before the `; ` is not allowed and fails the test that the command path must be absolute).

For the backward compatibility we could allow both a string and a list of string (I think pan allows this) and have the component do the right thing based on the actual value type....

**Comment by jrha** [comment]
Component side change done, needs schema change to complete.
Related to #1464.
