### ISSUE TITLE
ncm-cron 18.3.0: invalid /system/archetype/os test

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#1281]
As mentioned in https://github.com/quattor/template-library-core/pull/177, `config.pan` in `ncm-cron` is testing `/system/archetype/os` as a string when it was changed to a `dict` a while ago. This need to be fixed for `ncm-cron` be usable with Aquilon.

**Comment by ned21** [comment]
The correct fix is to switch to $^O which is I think a coding standard we agree long ago before we had standardised on /system/archetype/os being part of the template-library.
