### ISSUE TITLE
ncm-metaconfig: add libvirtd libvirt-guests configuration

### ISSUE THREAD

**Issue by alvarosimon** [quattor/configuration-modules-core#1287]
Include support to setup the config file `/etc/sysconfig/libvirt-guests`   from metaconfig. 
This will change the libvirt domains behaviour during hyps boots and shutdowns.

**Comment by jrha** [comment]
@alvarosimon do you have code for this?

**Comment by alvarosimon** [comment]
@jrha ah now I remember, not yet but I will open a new pr soon

**Comment by jrha** [comment]
Ok, feel free to push the milestone back if it looks like it will take too long

**Comment by alvarosimon** [comment]
@jrha this is fixed by #1345
