### ISSUE TITLE
ncm-network with #1308 fails on EL6

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#1323]
We discovered recently that #1308 which was introduced to support IPv6-only interfaces is causing problem on EL6. Unfortunately our initial tests were done on EL7 machines...

The problem seems to be that the main interface of the machine is shutdown when the configuration of the IPv6 interface is done. Thus `ccm-fetch` test fails and `ncm-network` rollback the configuration changes and restarts the interfaces. In addition to `ncm-network` failure, this results in the machine loosing its network connection during a couple of minutes every time the config module runs, i.e. at each Quattor deployment (as failed components are re-run by `ncm-ncd` until they succeed at each deployment).

We still don't have a clear picture of the problem but it affects our 2 machines running EL6 with an IPv6-only interface. It may be somewhat related to the fact that `onboot` is still `on` (former `ncm-network` version) rather than `yes` for the main interface, causing it to be reconfigured. But the same works on EL7. We at least found that a workaround is to set manually `onboot=yes` so that `ncm-network` considers the configuration up to date and does nothing with the interface.

Despite the fact that we see this problem on machines affected by the bug solved by #1308, it may be unrelated and due to a change in main interface at the same time as another one.

**Comment by jrha** [comment]
@jouvin did you get any further with understanding this?

**Comment by jrha** [comment]
@jouvin & @stdweird  I am tempted to declare this a non-issue unless there is any more evidence that logic within ncm-network is at fault and this was not an issue with the configuration being deployed.

**Comment by jrha** [comment]
Any more evidence of this in the last four months?

**Comment by jrha** [comment]
Closing. If this crops up again please re-open.
