### ISSUE TITLE
ncm-altlogrotate:  typo in ifempty key

### ISSUE THREAD

**Issue by aka7** [quattor/configuration-modules-core#1326]
ifempty key does not currently take effect. regardless of if set to true or false.
this is  due to typo in ifempty,  in file  src/main/perl/altlogrotate.pm,  ( see line 27 and 46 )

Tested locally by correcting the typo, 
when set to false, config has 'noifempty'.
no set to true, config has 'ifempty'.

**Comment by ned21** [comment]
Fixed in #1327
