### ISSUE TITLE
ncm-openstack: Fails on EL6

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#1356]
This seems pretty fatal as the underlying reason seems to be that the `MIME::Base64` module does not provide requires functionality for the OpenStack module.

If the build is not expected to function, we will need to exclude it from `build_all_repos` as it is currently breaking nightlies. We will also likely need to start building releases on both EL6 and EL7.
```
# VERBOSE No custom class NCM::Component::OpenStack::Keystone found for type identity flavour keystone (module load failed: "encode_base64url" is not exported b
y the MIME::Base64 module
#  "decode_base64url" is not exported by the MIME::Base64 module
# Can't continue after import errors at /usr/share/perl5/Net/OpenStack/Client/Identity/v3.pm line 13
# BEGIN failed--compilation aborted at /usr/share/perl5/Net/OpenStack/Client/Identity/v3.pm line 13.
# Compilation failed in require at /home/vafo45/quattordev/repos/configuration-modules-core/ncm-openstack/target/lib/perl/NCM/Component/OpenStack/Identity.pm li
ne 32.
```

**Comment by jrha** [comment]
@alvarosimon @stdweird would appreciate your thoughts on this

**Comment by stdweird** [comment]
@jrha it was only tested for el7. is there any real request to run it on el6? if not, don't build it for el7. we can add a perl requirement to make sure it fails on el6

**Comment by jrha** [comment]
No requirement from me, but the releases are currently built on EL6, so without extra work it won't be available in the release, which is fine for now, but I wanted to have a discussion about it.

**Comment by alvarosimon** [comment]
mm.. as @stdweird said we didn't test this in centos6, actually I think that the latest releases, queens and rocky are not supported in centos6, at least officially.

**Comment by jrha** [comment]
rc0 has built fine without ncm-openstack, so this isn't a show-stopper, but it would be nice to fix it.

**Comment by jrha** [comment]
Closing as won't fix due to lack of upstream support for EL6 and quattor/release#328 solving the nightly issues.
