### ISSUE TITLE
ncm-openstack: add magnum service support

### ISSUE THREAD

**Issue by alvarosimon** [quattor/configuration-modules-core#1397]
With Heat this will be useful to deploy kurbenetes and docker clusters.

https://docs.openstack.org/magnum/latest/

**Comment by Pansanel** [comment]
Nice idea. I already have developed a metaconfig based module. I have updated recently the code when migrating to Rocky and did not update my github fork.

**Comment by Pansanel** [comment]
In addition, [Barbican](https://docs.openstack.org/barbican/latest/) is a requirement for Magnum.

**Comment by alvarosimon** [comment]
true we have to include barbican as well...
