### ISSUE TITLE
ncm-ceph: Why are there two files called (C|c)ommands.pm in the same dir?

### ISSUE THREAD

**Issue by ned21** [quattor/configuration-modules-core#1418]
`ncm-ceph/src/main/perl/Ceph` contains both `Commands.pm` and `commands.pm`. This is confusing for the user but also causes problems when using the repo on an OS with case-insensitive filesystems (e.g. macOS).

**Comment by kwaegema** [comment]
@ned21 that probably wasn't the best idea indeed, but those lower-case files can now be removed, see #1462
