### ISSUE TITLE
ncm-spma: dnf plugin tries to remove current kernel-* packages

### ISSUE THREAD

**Issue by StephaneGerardVUB** [quattor/configuration-modules-core#1523]
Using version 21.4.1 under CentOS 8 Stream

**Comment by stdweird** [comment]
what do you mean here? it tries to and succeeds (should really never happen) or just tries to (not sure why that should ever happen)

spma output with debug 5 is required to see what happens, and also `rpm -qa` and `dnf repoquery -a --showduplicates kernel` before the run

**Comment by StephaneGerardVUB** [comment]
We gave it up with the plugin dnf.pm as we saw that is had not been updated for 2 years, and we decided to try yumdnf.pm instead.

**Comment by jrha** [comment]
We should document that `yumdnf` is considered the standard plugin for sites running EL8+.

**Comment by jrha** [comment]
I believe this is fixed by #1572.
