### ISSUE TITLE
ncm-spma: yumdnf backend: fails while trying to expand groups

### ISSUE THREAD

**Issue by StephaneGerardVUB** [quattor/configuration-modules-core#1524]
* Quattor release: 21.4.0
* OS: CentOS Stream release 8
* SPMA_BACKEND set to 'yumdnf' 
* Error message found in component-spma.log:
`[ERROR] Failed Group expansion: usage: dnf repoquery [-c [config file]] [-q] [-v] [--version]
...
dnf repoquery: error: unrecognized arguments: -g --grouppkgs`

**Comment by stdweird** [comment]
i think groups are deprecated in quattor (there should already be a deprecation warning during compilation), so it was never tested.
do you really need groups for something?

**Comment by StephaneGerardVUB** [comment]
We don't need groups. But the code of the spma component (more precisely in /usr/lib/perl/NCM/Component/spma/yum.pm) is calling an expand_groups function that fails.
