### ISSUE TITLE
ncm-modprobe: mkinitrd no longer available on rhel9, use dracut 

### ISSUE THREAD

**Issue by aka7** [quattor/configuration-modules-core#1577]
dracut package on rhel9  no longer provides mkinitrd binary.

rpm -ql dracut | grep mkinitrd 

I propose to consider using /usr/bin/dracut  if /usr/bin/mkinitrd is not available ?

* The version of the component you are using (rpm -q $component)
$ rpm -q ncm-modprobe
ncm-modprobe-21.12.1-1.noarch

* What OS version you are using (/etc/redhat-release or similar)
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 9.1 (Plow)

* Steps required to reproduce the problem
build a rhel9 host with modprobe changes.

* Actual result versus expected result
fails with
exec(mkinitrd, -f, /boot/initramfs-5.14.0-70.13.1.el9_0.x86_64.img, 5.14.0-70.13.1.el9_0.x86_64): No such file or directory

**Comment by duncanatwork** [comment]
Looks like mkinitrd is a shell wrapper that's a direct passthrough to dracut (at least back to RHEL6) for the single option we use, so we I think we can just swap out mkinitrd for dracut
