### ISSUE TITLE
ncm-opennebula: tm_mad 'ssh' should also be allowed for a fs datastore

### ISSUE THREAD

**Issue by StephaneGerardVUB** [quattor/configuration-modules-core#1584]
See:
https://github.com/quattor/configuration-modules-core/blob/e0300c409a0094eecbef2e4ba8f28878c019078e/ncm-opennebula/src/main/pan/components/opennebula/common.pan#L46

**Comment by alvarosimon** [comment]
@StephaneGerardVUB thanks for the hint, this was an old restriction it should be fixed in https://github.com/alvarosimon/configuration-modules-core/commit/8372c02dde7f881f1b00a25745d5d3e923c55795
