### ISSUE TITLE
ncm-opennebula: image generation for ONE 6.x

### ISSUE THREAD

**Issue by StephaneGerardVUB** [quattor/configuration-modules-core#1588]
Description of the problem:

With OpenNebula 6.6:
We are using an image FS datastore, and we would like qcow2 images. Even though we have set the diskdriver attibute to 'qcow2' in the Quattor tree under /system/opennebula, when we create VMs with the opennebula hook for aii, the disks are 'raw' type. The problem seems to come from the perl template imagetemplate.tt that sets attributes 'DRIVER' and and 'FSTYPE' to 'qcow2', but these two attributes are not referenced anymore in the official documentation for ONE 6.6, they seem to have been replaced by 'FORMAT'. Could you update this perl template so that it's compliant with new syntax?

**Comment by alvarosimon** [comment]
ok, this is odd, we are not running 6.6 yet, we are still running 6.4 in our clusters. We will upgrade to 6.6 our testbed soon and try it with ncm-opennebula. About your question indeed, the name was changed to `FORMAT` but we are still using the old name `DRIVER`. It is not documented but in 6.4 is working due the backwards compatibility with the old name (not sure if it will work the old name in 6.6 but probably it does). We will upgrade the tt file soon as well during our 6.6 tests (probably next week).
