### ISSUE TITLE
ncm-ssh 21.12.1: prohibit-password value not supported for PermitRootLogin

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#1603]
sshd option `PermitRootLogin` supports the value `prohibit-password` to allow root login through SSH with keys only. The schema doesn't allow this value.

**Comment by ned21** [comment]
Interesting, looks like this is just a rename of the existing option.

From the [man page](https://manpages.ubuntu.com/manpages/jammy/en/man5/sshd_config.5.html):

> PermitRootLogin
> 
> Specifies whether root can log in using [ssh](http://manpages.ubuntu.com/manpages/trusty/en/man1/ssh.1.html)(1). The argument must be “yes”, “without-password”, “forced-commands-only”, or "no”. The default is “yes”.
> 
> If this option is set to prohibit-password (or its deprecated alias, without-password), password and keyboard-interactive authentication are disabled for root.
