### ISSUE TITLE
ncm-nfs: start service nfs-server instead of nfs

### ISSUE THREAD

**Issue by jose-caballero** [quattor/configuration-modules-core#1618]
The nfs component attempts to start the service nfs, in line 
https://github.com/quattor/configuration-modules-core/blob/master/ncm-nfs/src/main/perl/nfs.pm#L482

That worked up to EL7, since the init file for nfs was just a link to nfs-server, which is the actual intended service.
From EL8, that link doesn't exist anymore, and nfs is deprecated in favour of nfs-server. 
Therefore, the component need to be updated to start the nfs-server daemon instead.

**Comment by jrha** [comment]
This should probably be made configurable in the schema and default to the legacy `nfs` if not set?
