### ISSUE TITLE
ncm-spma 23.6 on EL8/9: incorrect dependencies on YUM plugins

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#1662]
`ncm-spma` package has a dependency on `yum-plugin-versionlock` which does not do anything on EL8/9 with DNF. DNF plugin for achieving version locking is `python3-dnf-plugin-versionlock` that can't be installed as it conflicts with the YUM version.

**Comment by stdweird** [comment]
on our el88 hosts, we have
```
 rpm -q --provides python3-dnf-plugin-versionlock
config(python3-dnf-plugin-versionlock) = 4.0.21-19.el8_8
dnf-command(versionlock)
dnf-plugin-versionlock = 4.0.21-19.el8_8
dnf-plugins-extras-versionlock = 4.0.21-19.el8_8
python3-dnf-plugin-versionlock = 4.0.21-19.el8_8
python3-dnf-plugins-extras-versionlock = 4.0.21-19.el8_8
yum-plugin-versionlock = 4.0.21-19.el8_8
```
and only a dnf version lock plugin. OTOH, we don't have any `yum-plugin-versionlock` rpm in our repos. perhaps you have one, and it has a higher version then the one dnf-plugin-versionlock provides?

**Comment by jouvin** [comment]
@stdweird thanks for the info. I think I understand what happend: we have `yum-plugin-versionlock` (1.1.31) package installed by AII (Anaconda phase) from the distrib (because of our KS configuration). In the baseos repo we have the DNF version of the plugin you mentioned that provides the feature `yum-plugin-versionlock` but as it is already present it is not upgraded. We fixed the template configuring KS and to fix the problem without reinstalling I should have used `rpm -e --nodeps` instead of `dnf remove yum-plugin-versionlock` that removes also `ncm-spma`.

**Comment by jouvin** [comment]
For the record, I found the problem in our config that caused this misbehavior. We  had in our EL8 repositories a copy of the EL7 `yum-plugin-versionlock` that was overriding the one provided by Quattor which is an empty RPM with empty dependencies that allows the successful installation of `python3-dnf-plugin-versionlock`.
