### ISSUE TITLE
ncm-metaconfig 23.6: daemon name should be escaped/unescaped

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#1672]
Currently, the daemon names in `daemons` resource are interpreted as plain string. It works for all standard services but not for template services with multiple instance where an instance name is named `template_service@instance`, as `@` is an invalid character in a dict key. A workaround is probably possible using the `actions` but it would be good to support such service names which probably means that `metaconfig` should interpret the daemon names as escaped strings. It should not really pose backward compatibility problems as it is unlikely that a standard service name matches an escaped name.

**Comment by stdweird** [comment]
more things that slipped my radar...

i agree, fix should be as simple as replacing https://github.com/quattor/CAF/blob/master/src/main/perl/ServiceActions.pm#L116 with
```
    foreach my $escdaemon (sort keys %{$pairs || {}}) {
        my $daemon = unescape($escdaemon);
        my $action = $pairs->{$daemon};
```

and importing the unescape from some CCM module

also updating the docs somewhere i guess

**Comment by jrha** [comment]
Related to #1317, maybe we need a higher-level tracking issue for templated systemd services?
