### ISSUE TITLE
ncm-network nmstate: cannot configure IPv6

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#1675]
In v23.6.0 (and master modification until Jan 2024), if an interface has an IPv6 address configured, there is a message saying it is not supported. Any plan to support it? What is the workaround to configure an IPv6 address in the meantime?

**Comment by aka7** [comment]
@jouvin  Yes correct, that part wasn't done, left as TODO due to the urgency for us needing something working. Left for whoever hits it first :)  We don't use ipv6 hence wasn't urgent fo us at the time.

we probably should create issue for following too, which we dont use but I'm sure others will need it at some point.

    # TODO: ethtool settings to add in config file? setting via cmd cli working as is on dispatch.
    # TODO: add aliases ip addresses
    # TODO: interface and bridge_options
    # TODO: veth, anymore?

**Comment by jouvin** [comment]
@aka7 perfectly fine with me... We have the same urgency! Just wanted to be sure there is not a showtopper...

**Comment by jouvin** [comment]
@all does somebody started to work on IPv6 support in nmstate. It is becoming quite critical for us as we have to upgrade several servers configured with dual stack. If nothing has been started, I may have a look but I'd prefer not to duplicate some work in progress :-)

**Comment by aka7** [comment]
@jouvin  @stdweird 
created this for alias interfaces, https://github.com/quattor/configuration-modules-core/issues/1686

**Comment by jouvin** [comment]
@all sorry I missed the cachup meeting today, my previous meeting ended 15 mn late... On the IPv6 support, @guillaume-philippon told me today he had something almost working and was hoping to finalize it in  the coming days...

Michel
