### ISSUE TITLE
ncm-nmstate: VLAN name pattern too restrictive

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#1678]
`ncm-nmstate` changes in https://github.com/quattor/configuration-modules-core/issues/1667 recognizes as a VLAN any interface whose name starts with `vlan` but imposes a `.` before the VLAN ID, despite it is not an OS or `nmstate` requirement.

**Comment by jrha** [comment]
I believe that the kernel no-longer has any restriction other on interface naming other than being 15 characters or less, so we are free to follow any convention we can agree on.
