### ISSUE TITLE
ncm-grub: full rewrite needed!

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#232]
ncm-grub needs a full rewrite to at least:
- use the getTree() API
- use CAF::Process to call `grubby` command
- Cleanup unnecessary updates of grub configuration (for example if kernel args defined in the configuration are already set).

**Comment by jouvin** [comment]
It would be good to be able to manage `grub2` as we were able to do it with `grub`, in particular to be able to add kernel parameters. Digging around recently, I found that there is `grubby` in CentOS 7 too so it should be pretty easy to have to component managing both `grub` and `grub2`. I propose to have a look during 16.2 development cycle.

**Comment by stdweird** [comment]
we are using current `ncm-grub` to add /remove kernel parameters. what are you missing in particular?

**Comment by stdweird** [comment]
grub2 issue is covered in #1002
