### ISSUE TITLE
ncm-sysctl: support a quattor-owned file in /etc/sysctl.d

### ISSUE THREAD

**Issue by ned21** [quattor/configuration-modules-core#249]
Writing directly to /etc/sysctl.conf is problematic because if a key is removed from the profile, the file is not reverted to the default state. This could be done if the component instead wrote to a file called /etc/sysctl.d/quattor.conf and replaced the entire contents of that file every time ensuring any keys that are not longer set in the profile revert to their default.

NB: sysctl.d support was only added in RH6.2 and RH5.9

**Comment by jrha** [comment]
Shall we close as unnecessary?

**Comment by ned21** [comment]
No, I am planning to implement this since we need to maintain backwards compatibility with our current templates. Also we can switch between modes in template code depending on the OS version being configured.

**Comment by stdweird** [comment]
@ned21 we have some other components that have similar issues (e.g. `ncm-modprobe`, but in principle also httpd has this), so some generic solution could be beneficial.
the issue to solve imho is that you have more then one config file to manage, all in same format, and to run a single action upon change. it would be nice if TextRender could support this
