### ISSUE TITLE
ncm-mysql: user problem

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#250]
Some issues with ncm-mysql
* `FLUSH PRIVILEGES` after any user/privileges modifications
* mysql doesn't like `\` characters in the passwords. maybe check this in the schema?
* it's quite a hassle to create an empty database with just a user that has `ALL PRIVILEGES` rights on a none existing database. current trickery involves setting `createDb` to `false` and using `/dev/null` as `initScript/file`.
* the code allows `ALL` (just a string) for rights, but the schema enforces lists. might want to add the default privileges as default in schema (` = list('ALL PRIVILEGES')`)

**Comment by jrha** [comment]
Bump.

**Comment by ned21** [comment]
Let's clear the milestone on anything where there's not a realistic expectation of making progress, and it's not a must have feature/bug fix. Milestones can always be added to PRs if someone suddenly finds a patch down the back of the sofa...

**Comment by stdweird** [comment]
or close this issue as only #482 is left?
