### ISSUE TITLE
ncm-chkconfig: towards new ncm-chkconfig

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#307]
hi all,

(probably to be discussed/settled during workshop).

EL7 support is missing ncm-chkconfig support due to the fact that `chkconfig` (as opposed to `service`) has no full out-of-the-box support for systemd. in particular, the `--list` option is broken in all kinds of new ways. so the current component needs to be extended (or replaced by new one), and thus this raises the question how to deal with this.

main questions are:
A. move the logic to `CAF::Service`: although it makes sense, the code will be ugly, e.g. for current EL70 systems, we neeed both `chkconfig` and `systemctl` to get a list of all services if there any sysvinit only services in use. also `chkconfig --levels` acts different on systemd services.

B. simplify the schema: this will be a backwards incompatible issue, but the current schema is not understandable wrt what the component will do given certain combinations of settings.

if you have any proposals and/or opinions wrt A and/or B, post them here. it's important this work can be continued, and i don't want to discuss design in PRs anymore ;)

**Comment by jrha** [comment]
Related to this: at the workshop we discussed a new simpler schema somewhere like `/software/services` or `/system/services` to be consumed by all "service" components that only provides very basic "this service should/should not be running" leaving services that require something more complex to the schema of the appropriate component (chkconfig, systemd or smf).

**Comment by jrha** [comment]
@stdweird how much of this is included in/covered by `ncm-systemd`?
Does this need bumping to 15.6?

**Comment by stdweird** [comment]
`ncm-systemd` now does something similar with the services defined in `/software/component/chkconfig`. reading the state from another path (and with other schema) is only a matter of wrting a mapper from the `/system/services` to the description used internal in the systemd component.

see e.g. the inner loop of https://github.com/quattor/configuration-modules-core/blob/master/ncm-systemd/src/main/perl/Systemd/Service/Chkconfig.pm#L209

**Comment by jrha** [comment]
In which case I will open a new issue for the next release and consider this one closed.
