### ISSUE TITLE
ncm-metaconfig: integrate hpcugent's config-templates repository into the ncm-metaconfig subtree

### ISSUE THREAD

**Issue by piojo** [quattor/configuration-modules-core#311]
The Quattor org will take over @hpcugent's config-templates repository. We'll ship those templates with ncm-metaconfig itself. We need to:

* Modify the POM file to package all those TT files.
* Modify the release script to add the Pan code to the template libraries.
* Run the unit tests for those TT files.

**Comment by jrha** [comment]
> * Modify the POM file to package all those TT files.

Fixed in #391 (specifically e0bd6c9c34c6a9e50ec75f42ef429cb49b8fca9b) and verified.

> * Modify the release script to add the Pan code to the template libraries.

quattor/release/#68 is tracking this.

> * Run the unit tests for those TT files.

The unit tests added as part of #398 do get run by `mvn test`

**Comment by stdweird** [comment]
The 2 main things that are not complete is the migration of the opennebula TT files to `ncm-opennebula` (see opennebula PRs for that) and the elasticsearch TT files (need new maven-tools for that; and a PR with the ES config and schema).
so i guess this will be closed in 15.2

**Comment by jrha** [comment]
I think it would be better to track opennebula and elasticsearch in seperate issues and close this one.
