### ISSUE TITLE
ncm-opennebula: create the oneadmin .ssh/config with controlmaster

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#325]
Create the `.ssh/config` file for the `oneadmin` user (benefits both component and opennebula)

**Comment by alvarosimon** [comment]
This feature is already handled by Quattor ssh_config

**Comment by stdweird** [comment]
make sure it is used in the example templates then :smile:

**Comment by alvarosimon** [comment]
ah.. yep :smile:
