### ISSUE TITLE
ncm-ceph: validate radosgw configuration schema

### ISSUE THREAD

**Issue by kwaegema** [quattor/configuration-modules-core#333]
radosgw config schema not validated yet in #320 . The config parameters should be checked and tested

**Comment by jrha** [comment]
@kwaegema it would be good to have this in 15.6.

**Comment by kwaegema** [comment]
This was that issue that requires some input from people using the radosgw :smile: If I get a list of config parameters with their possible values needed for radosgw, I will gladly put it into the scheme!

**Comment by jrha** [comment]
@gvasilak can you help?

**Comment by gvasilak** [comment]
@jrha I will look into it, but as radosgw isn't currently a priority it might be a few weeks.
@kwaegema how would you like the list?

**Comment by jrha** [comment]
Well 15.6 is June, so a few weeks is fine.

**Comment by gvasilak** [comment]
@kwaegema just so I'm clearer on what you need: apart from what is available in the first section of [this](http://ceph.com/docs/master/radosgw/config-ref/) what else do you need?
Is it a case of needing the exact set of possible values for each variable?
Most conform to common data type, file path, URL, IP address or hostname formats.

**Comment by kwaegema** [comment]
Two thinks are needed to validate the radosgw config: 
- a schema type: this is like the ``type ceph_cluster_config`` in  https://github.com/quattor/configuration-modules-core/blob/master/ncm-ceph/src/main/pan/components/ceph/schema.pan#L210.
Ideally, you can provide this pan fragment for me, but if you're not familiar enough with the pan syntax, I'd like to have for each config parameter: is it mandatory, type (with ranges or matching some values or expression), does it have to have a default value and if yes, which. It probably comes down to parsing that section in the ceph doc, but I know from experience it is not always up to date or has sometimes wrong defaults.. So I think it is better someone with knowledge of radosgw provides this than blindly copying the doc :smile: 
- Some perl code to run the function that does some sanity checks and compares the configs. I can do this very easily. If there are values that may not change after initial deploy (eg an id or a name..) you should also provide me this, I have also a function that checks that :)

**Comment by gvasilak** [comment]
Hammer now embeds `civetweb` within the `radosgw` daemon and `ceph-deploy` is able to deploy them based on `ceph.conf`. 
I think it's worth looking into getting the component to support this new functionality.
I'll be looking into the radosgw config in the coming two weeks.
