### ISSUE TITLE
ncm-autofs : Not doing the right things when trying to configure a direct mount

### ISSUE THREAD

**Issue by StephaneGerardVUB** [quattor/configuration-modules-core#335]
I've tried this setting : `/software/components/autofs/maps/kalitest/type = "direct"`
for one of my autofs shares. But then, ncm-autofs adds the following line to /etc/auto.master:
`/kalitest      direct:/etc/auto.direct`
That's not correct. According to "man 5 auto.master", the right way should be :
`/-    /etc/auto.direct`
There's also a problem in the file /etc/auto.direct. It says :
`kalitest    myfileserver:/mydirectory`
while it should say :
`/kalitest    myfileserver:/mydirectory`

**Comment by jrha** [comment]
Lets try and sort this out for 15.2, it looks a first glance like it might take some fiddling around to achieve correct behaviour.

**Comment by jrha** [comment]
The following note appears in `features/nfs/client/autofs.pan` from `template-library-grid`:
```pan
# An indirect map is used instead of a direct map because direct map
# support on Linux (as of SL3/4) is broken and disabled by default.
```
Which probably explains why this bug has not been seen before.
