### ISSUE TITLE
ncm-ceph unit tests depend on Git/Repository.pm not found on SL6

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#344]
It seems that `ncm-ceph` unit tests (in the current master) depend on perl module `Git/Repository.pm` which is not available in perl-Git as provided on SL6... I was not able to find it in another package.

**Comment by jrha** [comment]
See quattor/release#62

**Comment by jrha** [comment]
The package is now available from http://yum.quattor.org/externals/noarch/el6/, is this sufficient to close this issue?
