### ISSUE TITLE
ncm-download 14.10.0-rc2: failing download.t on SL6

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#372]
In 14.10.0-rc2 (https://github.com/quattor/release/issues/59), `ncm-download` fails unit test `download.t` on a SL6 machine with 14.10.0-rc2 installed.

I had a quick look but didn't find the reason... This is a minor issue, I set milestone to current release in case somebody has the time to look at it and find a trivial cause. Else can be postponed to 14.12, IMO.

**Comment by jrha** [comment]
Bumped to 15.2

**Comment by jouvin** [comment]
The problem is still there in 15.2.0-rc6 and prevents `mvn test` for the whole repo to run successfully.

**Comment by stdweird** [comment]
@jouvin can you me send the output of the following
```
cd ncm-download
QUATTOR_TEST_LOG_DEBUGLEVEL=5 QUATTOR_TEST_LOG_CMD_MISSING=1 QUATTOR_TEST_LOG_CMD=1 mvn clean test -Dunittest=download.t -Dprove.args='-v'
```
and the verbose perl Trace call

**Comment by jouvin** [comment]
This morning it works!!! In my previous test, I didn't execute the `clean` phase: may be something left from the previous version... I'm a bit surprised but I close this issue and will reopen it if it happens again.
