### ISSUE TITLE
ncm-metaconfig 14.10.0-rc2: uninitialized value in error.t

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#373]
When running unit tests of `ncm-metaconfig`, there is the following message:
```
Use of uninitialized value $tplname in concatenation (.) or string at /usr/lib/perl/CAF/TextRender.pm line 234.
```

Milestone set to 14.10 (https://github.com/quattor/release/issues/59) in case it is trivial to fix but can be postponed to 14.12 if necessary...

**Comment by jrha** [comment]
Bumped to 15.2

**Comment by stdweird** [comment]
@jouvin can you retest this?

**Comment by jrha** [comment]
@jouvin any update?

**Comment by jrha** [comment]
@jouvin can you update this issue please.

**Comment by jouvin** [comment]
Sorry for overlooking it. I don't see the problem anymore with the master branch (still using build tools 1.42). I close it.

**Comment by jrha** [comment]
Thanks!
