### ISSUE TITLE
ncm-postfix 14.10.0-rc2: cleanup error in component.t

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#374]
`ncm-postfix` 14.10.0-rc2 unit tests report the following error in `component.t`:
```
        (in cleanup) Can't locate object method "report" via package "NCM::Component::postfix" at /usr/lib/perl/CAF/FileWriter.pm line 189.
        (in cleanup) Can't locate object method "report" via package "NCM::Component::postfix" at /usr/lib/perl/CAF/FileWriter.pm line 189.
src/test/perl/component.t ... ok
```

Set to milestone 14.10 (https://github.com/quattor/release/issues/59) in case this is trivial to fix but feel free to postpone to 14.12.

**Comment by jouvin** [comment]
I can imagine this is related to the fact that the logger is note yet initialized... will try to have a look but if somebody else as an idea, please tell it!

**Comment by stdweird** [comment]
@jouvin i don't get the error using `QUATTOR_TEST_LOG_DEBUGLEVEL=3 mvn clean test -Dprove.args=-v 2>&1 |grep report`
(the logger in the unittest received some cleanup in 1.42 build-scripts)

**Comment by jouvin** [comment]
I don't reproduce it either with 15.2... Closing it.
