### ISSUE TITLE
ncm-symlink: clarify intended behaviour of replace

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#381]
the current behaviour of `ncm-symlink` can't really be derived form the pod
the schema allows all suboptions, the code however doesn't; so ideally the schema is restricted or at least the (intended) behaviour made clear in the pod (and some examples are welcome too; e.g. what is the exact behaviour of `replace = nlist('all', 'yes')`?).

because of the power of `ncm-symlink`, this has to be clarified and then the code checked with the intended behaviour.
in particular, the "eastereggs" `none=no` and `all=no` should be documented/fixed

**Comment by jrha** [comment]
This just needs updated documentation.

**Comment by jouvin** [comment]
I'm working on it...
