### ISSUE TITLE
ncm-metaconfig: Include elasticsearch TT files

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#404]
Split off from #311 

Needs new maven-tools and a PR with the ES config and schema.

**Comment by jrha** [comment]
@stdweird how feasible is this for the current release?

**Comment by stdweird** [comment]
it's a cleanup of https://github.com/stdweird/quattor-SCDB-ugent/blob/master/cfg/non-grid/hpc/common/elasticsearch/schema.tpl with some unittests. but i'd like to unittest actual yaml code with updated ccm.
i'm ok with moving this to 15.6
