### ISSUE TITLE
ncm-modprobe: misleading documentation

### ISSUE THREAD

**Issue by victor-mendoza** [quattor/configuration-modules-core#412]
Hi,

  Currently the documentation for ncm-modprobe mentions the configuration files "/etc/modprobe.conf" and  "/etc/modprobe.d/ncm-modprobe.conf", neither of which are generated.

  The actual configuration file seems to be configurable and defaults to: "/etc/modprobe.d/quattor.conf"

  Regards,
  Victor

**Comment by jrha** [comment]
Fixed by #449.
