### ISSUE TITLE
ncm-authconfig: missing parameter for sssd

### ISSUE THREAD

**Issue by JulienNauroy** [quattor/configuration-modules-core#427]
Hi,

I'm trying to configure sssd using ncm-authconfig.
In the [domain/X] section, I'd like to use "cache_sensitive" but it's not in the Quattor schema file.
Could you please add it in a next release ?

BTW, my reference configuration file is like 20 lines long. As an example, [nss] and [pam] sections are empty. I cannot reproduce the same configuration file since ncm-authconfig provides and outputs default values for most values. Why is that so ?

Cheers,
Julien

**Comment by jrha** [comment]
We can of course add `cache_sensitive`, or you could open a pull-request for it yourself, which might be quicker.

**Comment by stdweird** [comment]
@JulienNauroy i'll try to fix this asap, but wrt the defaults, as to why that is the case, it's a matter of opinion (esp how to keep the values the same across OSes with different versions of SSSD).
if there are issues with the defaults, they should get fixed ofcourse. maybe open a new issue to allow to set a very minimal config to discuss/address this problem (but that won't make it in 15.4 :smile: ).

**Comment by stdweird** [comment]
@JulienNauroy euhm it seems to be there
https://github.com/quattor/configuration-modules-core/blob/master/ncm-authconfig/src/main/pan/components/authconfig/schema.pan#L443
what is not working for you?

**Comment by jrha** [comment]
@JulienNauroy did you really mean `cache_sensitive` or is `case_sensitive` what you intended?

**Comment by stdweird** [comment]
@jrha i didn't even saw @JulienNauroy asked for `cache_sensitive`. what sssd version should have this? (or what man page?)

**Comment by jrha** [comment]
I don't know, I can't find it in any documentation.

**Comment by stdweird** [comment]
@jrha me neither, i googled it, there's a french blog that has it in an example (but it suggests it's in the default sssd.conf on el6) 
if it's really an option, should be easy fix and can be done in any 15.4 rc. lets wait a bit more

**Comment by stdweird** [comment]
there's is no default sssd.conf on el6, and `cache_sensitive` seems not supported by the python api
```
[root@localhost ~]# cd /usr/share/sssd
[root@localhost sssd]# ls
sssd.api.conf  sssd.api.d
[root@localhost sssd]# grep -r cache *
sssd.api.conf:krb5_rcache_dir = str, None, false
sssd.api.conf:enum_cache_timeout = int, None, false
sssd.api.conf:entry_cache_nowait_percentage = int, None, false
sssd.api.conf:memcache_timeout = int, None, false
sssd.api.conf:cache_credentials = bool, None, false
sssd.api.conf:entry_cache_timeout = int, None, false
sssd.api.conf:account_cache_expiration = int, None, false
sssd.api.conf:#Entry cache timeouts
sssd.api.conf:entry_cache_user_timeout = int, None, false
sssd.api.conf:entry_cache_group_timeout = int, None, false
sssd.api.conf:entry_cache_netgroup_timeout = int, None, false
sssd.api.conf:entry_cache_service_timeout = int, None, false
sssd.api.conf:entry_cache_autofs_timeout = int, None, false
sssd.api.conf:entry_cache_sudo_timeout = int, None, false
sssd.api.d/sssd-ldap.conf:ldap_purge_cache_timeout = int, None, false
sssd.api.d/sssd-ipa.conf:ldap_purge_cache_timeout = int, None, false
sssd.api.d/sssd-ipa.conf:krb5_ccachedir = str, None, false
sssd.api.d/sssd-ad.conf:ldap_purge_cache_timeout = int, None, false
sssd.api.d/sssd-ad.conf:krb5_ccachedir = str, None, false
sssd.api.d/sssd-krb5.conf:krb5_ccachedir = str, None, false
[root@localhost sssd]# grep -r sensitive *
sssd.api.conf:case_sensitive = bool, None, false
```

**Comment by JulienNauroy** [comment]
I'm sorry I can't tell you much more about cache_sensitive, It's something that's used in my site's configuration and I wanted to reproduce.

I'll see if I can have more info from the sysadmin.

**Comment by jrha** [comment]
I suspect this option does not actually exist and is a typo which has survived many copy and pastings.

```
# strings `which sssd` | grep cache_sensitive

# strings `which sssd` | grep case_sensitive
case_sensitive

# strings `which sssd` | grep sensitive
case_sensitive
Local ID provider does not support the case insensitive flag
Domain is case-insensitive; will add lowercased aliases

```

**Comment by JulienNauroy** [comment]
@jrha You're probably right. I'll double check with the sysadmin but in the end it looks like a typo.

I agree with @stdweird, defining default values for ncm-authconfig is a matter of choice, and fits Quattor's philosophy to control the configuration, although making the result file less readable.

I'm closing the ticket. It has become irrelevant.
