### ISSUE TITLE
Handle non-EL5 code

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#441]
There are a number of components that won't work on EL5 due to perl 5.10-isms
- ncm-ceph
- ncm-icinga
- ncm-opennebula
- ncm-systemd

It makes no sense for these to ever run on EL5, but the tests will fail.
We need a way to be able to exclude them during EL5 tests (but then the release process can't be performed on EL5)

**Comment by jrha** [comment]
The release process is currently run on EL7, it will probably always be run on the latest OS we support, so I don't see this as an issue.

**Comment by jrha** [comment]
@stdweird - As the tests run on EL5 now, are we in a position where this is "done"?

**Comment by stdweird** [comment]
@jrha the tests don't run on EL5.
i was sort of hoping that the release process ran the `build_all_repos` on at least the EL5/6/7 to verify this.

**Comment by jrha** [comment]
Ok, my mistake

**Comment by jouvin** [comment]
Does something need to be done for this issue... Conversation is a bit cryptic!

**Comment by stdweird** [comment]
@jouvin `mvn test` runs tests for all components, we need a way to exclude certain tests because they will fail due to the perl version shipped by the OS (and there's no point in making them run on said OS).

maybe there's a way to exclude certain components from the module list (or have a minimal modules list that runs everywhere and test more modules on e.g. EL6 and EL7)? 

i modified the build_all_repos script to do filter them out, but that's not really clean
https://github.com/quattor/release/pull/88/files#diff-a6c7fe45e58347ad6110fa660ecdcb8dR58
with this modification, i can test the 15.4 rcs on EL5, so this can be moved to later release if there's no easy/quick way to achieve this

**Comment by jouvin** [comment]
Thanks. This was my understanding of the problem from the initial description but from the conversation it was not clear whether there was still an action to do... I'll try to think about how this could be done at the Maven level but this may be quite complex. Do you want only to exclude the test phase when Maven is run or do you want to make the configuration module list depending on the OS version (which may be trickier)?

**Comment by stdweird** [comment]
exclude the test phase is fine, but i'm not sure what this means. (eg `mvn package` should also be possible, and ideally not make rpms for the non-tested modules)
but i'll be happy with anything that means not editing the pom.xml :smile:

**Comment by jouvin** [comment]
As for the tests in build tools repo, we can probably make the tests for some components conditional, based on a variable reflecting the os version... I have to think more about it...

**Comment by jrha** [comment]
@stdweird has done a lot to solve this issue, how much is left to be done?

**Comment by stdweird** [comment]
to be clear, i worked around the issue, not solving anything (but we can run the tests on EL5)

**Comment by jrha** [comment]
Bump it, or close it?

**Comment by jrha** [comment]
@stdweird Bump it, or close it?

**Comment by ned21** [comment]
I think we need to make the tests run on EL5 so can use them to make sure that components that are required on EL5 have not been broken by a regression. Tests for code known not to support older platforms will need to call that out via some Test::* trickery.

**Comment by stdweird** [comment]
See example commit to exclude a non-el5 component https://github.com/quattor/release/commit/037a42bce0afd2a1625f1fa27dd45eda757cb995

**Comment by jouvin** [comment]
Check if we could use a Maven activation property based on a file existence to disable building/testing of some components based on an OS version.

**Comment by jrha** [comment]
Discussed at March 2017 workshop, agreed to selectively switch the compile and test of affected components in Maven.

**Comment by jrha** [comment]
Mostly resolved by quattor/release#299 back in 17.8.
Solving the more general case in Maven isn't worth the effort now that EL5 is long gone.
