### ISSUE TITLE
ncm-network: realhostname not used

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#462]
Current realhostname code
```perl
if ($config->elementExists($path."/realhostname")) {
    $text .= "HOSTNAME=".$config->getValue($path."/hostname")."\n";
}
```
which has behaviour that setting `realhostname` to anything sets the short hostname as `hostname`.
fixing this bug might break current templates that rely on this "feature".

**Comment by jrha** [comment]
Ugh, what the what? That's horrible.
