### ISSUE TITLE
ncm-ntpd: doesn't start service as no default for servicename

### ISSUE THREAD

**Issue by drossy** [quattor/configuration-modules-core#473]
Servicename is optional in the schema, but there is no default value, so the time service isn't actually started unless an explicit value is entered for servicename. Which took me by surprise.

There is a comment in the docs that Solaris uses a different service name, but @jrha tells me that OS-specific defaults are possible, so is it possible to add a default to servicename so that the time service is started when configured using ncm-ntpd?

**Comment by stdweird** [comment]
to have a running service, do not forget to enable the service via chkconfig component. `ncm-ntpd` only supports restarts due to config changes. it is not the task of the component to start the service.

**Comment by drossy** [comment]
Okay, but without a servicename defined it won't restart the time server when the config is updated, which I'd say is unexpected.

Also, though this is possibly tangential, but it appears to do a restart of the service i.e. it will start a stopped service, should it possibly be condrestart?

**Comment by jrha** [comment]
So the code already looks like it should so the right thing, setting `servicename` shouldn't be required.
```perl
Readonly::Scalar my $DEFAULT_SERVICE    => '${project.artifactId}';
Readonly::Scalar my $DEFAULTSOL_SERVICE => 'svc:/network/ntp';
```
```perl
	if (exists $cfg->{servicename}) {
		$servicename = $cfg->{servicename};
	} elsif ($^O eq 'solaris') {
		$servicename = $DEFAULTSOL_SERVICE;
	} else {
		$servicename = $DEFAULT_SERVICE;
	}
```

**Comment by jrha** [comment]
Can you check that you have
```perl
Readonly::Scalar my $DEFAULT_SERVICE    => 'ntpd';
```
in `/usr/lib/perl/NCM/Component/ntpd.pm`

**Comment by jrha** [comment]
Running with verbose and/or debug should log the command that the component is (or isn't) trying to run if you feel like going deeper down the rabbit hole.

**Comment by drossy** [comment]
Hmm, apologies  - on double checking the component is restarting when it makes changes to the config file

**Comment by jrha** [comment]
Might still be worth switching to condrestart?
