### ISSUE TITLE
ncm-opennebula not in 15.2

### ISSUE THREAD

**Issue by samary** [quattor/configuration-modules-core#492]
Hi,

I cannot find the ncm-opennebula rpm in the 15.2 yum repo.
It seems the version of this component was not bumped since 14.10
Can someone bump this to 15.2 or we have to wait for 15.4 to have it back ?

Thanks

**Comment by jrha** [comment]
ncm-opennebula was only introduced as a supported core component in #399 (5f650c00ef943aebcf2a85059d24a17c2d49425c to be exact), so yes it will be in 15.4, it was never in 14.10, so I'm not sure what you mean by "bumped"...

**Comment by jrha** [comment]
Fixed in #399 by 5f650c00ef943aebcf2a85059d24a17c2d49425c.

**Comment by samary** [comment]
Sorry for the confusion, I saw 14.10 in the pom.xml version under the 15.2 release which is not something I expected to see.

**Comment by jrha** [comment]
Yeah that's just an artifact of copy and paste from another pom I think! :smile:

**Comment by stdweird** [comment]
@samary if only we could get the rpms from jenkins out of jenkins. anyway, rc should arrive soonish i guess, if needed, i can send your our rpms (to add to the confusion, we run `ncm-opennebula-14.10.0-rc2_SNAPSHOT20150407065929.noarch` :grinning: )

**Comment by samary** [comment]
@stdweird Thanks, we have build the RPM on our site, I just wanted to point this out.
