### ISSUE TITLE
ncm-spma 15.4.0-rc1: repository name validation too restrictive

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#495]
In 15.4.0, there is a validation rule for repository names. Unfortunatly, it lacks `.` in the list of allowed characters...

This is a blocking issue for 15.4.0 (https://github.com/quattor/release/issues/85).

**Comment by jrha** [comment]
Can you provide examples of repositories where this is a problem?
It is only a name after all.

**Comment by jrha** [comment]
The validation rule was added by #451 to fix #409.

**Comment by jouvin** [comment]
I have certainly nothing against name validation! It's a good addition. An example is Quattor repository names! At LAL, they are based on the version name, something like `quattor_15.4.0-rc1`. Thus we need the `.` in addition to other characters.

**Comment by jrha** [comment]
Thanks, to be clear, the validation is needed because the name is also used as the repository id.
