### ISSUE TITLE
ncm-symlink reporting errors when it shouldn't?

### ISSUE THREAD

**Issue by JulienNauroy** [quattor/configuration-modules-core#508]
When using ```exists = true```, such as in the examples, ncm-symlink will report an error if the symlink already exists. This means ncm-ncd will report this type of error everytime but the first:
```[ERROR] link xxx already exists and replacement is not allowed```

I suggest reporting an error only if the symlink does not point to the expected location or else the module is bound to report errors as soon as it has created the link.

**Comment by jouvin** [comment]
The documentation has been recently improved and the new doc will be part of the upcoming 15.4. But `exists` is not about the symlink but its target. You need to specify the `replace`option: see https://github.com/quattor/configuration-modules-core/blob/master/ncm-symlink/src/main/perl/symlink.pod for details.
