### ISSUE TITLE
ncm-ceph: ceph.conf boolean value for mon_cluster_log_to_syslog

### ISSUE THREAD

**Issue by kwaegema** [quattor/configuration-modules-core#517]
They changed a boolean value to a string type: See http://comments.gmane.org/gmane.comp.file-systems.ceph.user/20421.

Since Config Tiny write booleans as 1 or 0, this no longer works for this variable in the last version(s) of ceph. If `mon_cluster_log_to_syslog` needs to be a string, I should make it so in the schema (with at least accepted values `true` and `false`)

**Comment by kwaegema** [comment]
They hopefully gonna fix this: http://tracker.ceph.com/issues/12325

**Comment by stdweird** [comment]
@kwaegema the ceph is in state merged. is this in a release yet? stable update or otherwise?

**Comment by kwaegema** [comment]
Not yet released afaik. It is in the milestone of Infernalis. I asked if it will be backported

**Comment by kwaegema** [comment]
This is fixed in Infernalis.
