### ISSUE TITLE
Quattor 15.4.0 authconfig component problem

### ISSUE THREAD

**Issue by seraf1** [quattor/configuration-modules-core#529]
Hi,
In Quattor 15.4.0, the authconfig component schema is defined as follows:
```pan
/type authconfig_pamadditions_line_type = {
  "order"       : string with match(SELF, '^(first|last)$')
  "entry"       : string with match(SELF, '\S+\.so$')
};
```

while in 15.2.0, it corresponds to it:
```pan
type authconfig_pamadditions_line_type = {//
  "order"       : string with match(SELF, 'first|last')//
  "entry"       : string with match(SELF, '\S+\.so')//
};
```

What makes the following statement fails:
```pan
"/software/components/authconfig/pamadditions/system"=nlist(
    "conffile","/etc/pam.d/sshd",
    "section","account",
    "lines",list( nlist(
           "order","first",
           "entry","required      pam_access.so accessfile=/etc/security/access_sshd.conf"
    ))
);
```

**Comment by stdweird** [comment]
it's a bug, but it needs an improved regex in schema. probably something like 
```pan
"entry"       : string with match(SELF, '^\s*\w+\s+\S+\.so(\s|$)')
```
but there's a small issue with the component code too. the component will assume anything matching `(\S+\.so)` as the module (should be at least `(?:^|\s+)(\S+\.so)(?:\s|$)`).

@seraf1 looking at the code, you should be able to use the regex from the 15.2 schema to do what you want (or try the above one and let us know :smile: ).

**Comment by seraf1** [comment]
Hello,

In fact, I remove the $ at the end of the regular expression and it 
seems ok.

Regards,

Philippe


Le 17/06/2015 13:27, Stijn De Weirdt a écrit :
>
> it's a bug, but it needs an improved regex in schema. probably 
> something like
>
> |"entry"       : string with match(SELF, '^\s*\w+\s+\S+\.so(\s|$)')
> |
>
> but there's a small issue with the component code too. the component 
> will assume anything matching |(\S+\.so)| as the module (should be at 
> least |(?:^|\s+)(\S+\.so)(?:\s|$)|).
>
> @seraf1 <https://github.com/seraf1> looking at the code, you should be 
> able to use the regex from the 15.2 schema to do what you want (or try 
> the above one and let us know :smile: ).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/quattor/configuration-modules-core/issues/529#issuecomment-112760594>.
>

-- 
*SERAPHIN Philippe*
L.A.P.P.
9 chemin de Bellevue
BP 110
74941 Annecy le Vieux Cedex

Tél. : (+33) (0)4 50 09 17 38
/Fax : (+33) (0)4 50 27 94 95/
@ : philippe.seraphin@lapp.in2p3.fr <mailto:philippe.seraphin@lapp.in2p3.fr>
