### ISSUE TITLE
ncm-ntpd - Use servers names instead of resolved IPs

### ISSUE THREAD

**Issue by samary** [quattor/configuration-modules-core#531]
Hello,

I see in the component code, we translate servers names to IP in order to put them in the ntp.conf (https://github.com/quattor/configuration-modules-core/blob/master/ncm-ntpd/src/main/perl/ntpd.pm#L64).
Using pools (time.belnet.be, be.pool.ntp.org, ...) will resolve an IP from the round-robin DNS, which may lead to issues if the resolved server is down. 
Couldn't we use server names (via an option or by default) in the config file instead of IP's addresses ?

**Comment by jrha** [comment]
Having just discussed this with @stdweird, we agree that the current behaviour seems odd and not useful, we have flagged this as a bug and propose to no longer resolve the hostnames.

We could introduce a boolean to preserve the legacy behaviour if anyone needs it...

**Comment by ned21** [comment]
We would be happy to see this move to names and not use IPs.
