### ISSUE TITLE
ncm-fsprobe: schema is garbage

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#555]
It seems to mostly be a clone of the ncm-useraccess schema where `useraccess` has been replaced by `fsprobe` it certainly doesn't match the documentation.

I suspect no-one is using the component, because it is probably unusable, can we ditch it?

**Comment by ned21** [comment]
It looks like its for a CERN tool called [fsprobe](http://cds.cern.ch/record/1457989/files/chep%202012%20CERN%20infrastructure%20final.pdf?version=1) and so unless they released it, this component can be removed.

**Comment by stdweird** [comment]
@ned21 seems they did https://gitlab.com/groups/fsprobe
but i guess nooone is using it, maybe we can move it to some legacy branch? or people can always revert this PR at a lter moment

**Comment by jrha** [comment]
We actually run fsprobe at RAL, but we apparently never used the component to configure it.
