### ISSUE TITLE
ncm-ceph: ownership of known_hosts file when first talking to other monitors

### ISSUE THREAD

**Issue by GRyall** [quattor/configuration-modules-core#586]
We have just changed our `deploy_host`, this was relatively simple, but to make the component work we had to change the ownership of `/home/ceph/.ssh/known_hosts` from root to ceph. It wouldn't talk to the other monitors until we did this, is this something that the component could check before trying to add anything to the `known_hosts` file?

**Comment by jrha** [comment]
Fixed by #595, but the fixes line was not written correctly.
