### ISSUE TITLE
ncm-ccm: ccm-fetch cannot handle stdin as configfile

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#597]
the test of the new cofngifile in ncm-ccm uses ccm-fetch with configfile to test piped via stdin. but this pipe is supposed to be read twice: once by CAF::Application, once by CCM::CCfg, which is not possible

**Comment by stdweird** [comment]
blocker for https://github.com/quattor/release/issues/109

**Comment by ned21** [comment]
Also /proc/self is not valid on Solaris.
