### ISSUE TITLE
ncm-ceph : problem with the template ceph-hosts.pan in the examples

### ISSUE THREAD

**Issue by StephaneGerardVUB** [quattor/configuration-modules-core#617]
I don't understand these lines :
https://github.com/quattor/configuration-modules-core/blob/master/ncm-ceph/src/examples/ceph-hosts.pan#L154-L159
The effect is to add an osd for each journal disk.

**Comment by kwaegema** [comment]
hmm, CEPH_JOURNAL_DISKS is the variable used for this, because we used the same disks for journals as for metadata. so this means actually metadata disks. But I fear these examples are quite old and I surely should update them.. I created #618 for this

**Comment by kwaegema** [comment]
@StephaneGerardVUB I added templates that can be used for ceph in the examples repo (https://github.com/quattor/template-library-examples/pull/29). I hope this makes it easier to set up a ceph cluster

**Comment by kwaegema** [comment]
Since examples are updated, I will close this. If there are further questions, please (re)open issue
