### ISSUE TITLE
ncm-network: ovs_extra is not set correctly

### ISSUE THREAD

**Issue by alvarosimon** [quattor/configuration-modules-core#651]
If you set ovs_extra conf from quattor the component encloses the text into single quotes instead of double quotes, for example if you set in quattor:
> "ovs_extra", 'set Interface $DEVICE type=internal',

you get from the network conf file:
> OVS_EXTRA='set Interface $DEVICE type=internal'

and the variable is not expanded, from OVS logs:
> ovs-vsctl: ovs|00001|vsctl|INFO|Called as ovs-vsctl -t 10 -- --may-exist add-br br100 -- set Interface $DEVICE type=internal
> ovs-vsctl: ovs|00002|vsctl|ERR|no row "$DEVICE" in table Interface

It should be:
> OVS_EXTRA="set Interface $DEVICE type=internal"

It could be fixed from network.pm just including double quotes:
> 294                     $text .= "OVS_EXTRA=\"$net{$iface}{ovs_extra}\"\n";

**Comment by stdweird** [comment]
why not set the device name (why rely on the variable)?

**Comment by alvarosimon** [comment]
@stdweird that's another option, do not use variables at all within `ovs_extra`, but I have used the same conf that is provided by redhat. In that case it should be documented.

**Comment by stdweird** [comment]
for me it  is fine to use the variable, if this is the recommended way to do things
