### ISSUE TITLE
ncm-network: schema should allow localhost.localdomain as a valid hostname value

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#657]
The network core schema enforces that `/system/network/hostname` (used to define `HOSTNAME` variable in `/etc/sysconfig/network`) is a short name. This makes impossible to use the "magic value" `localhost.localdomain` that result in the hostname being defined to the name corresponding to the first interface IP address.
This would be good to make this value possible. It is particularly useful when building VM images for a cloud.

**Comment by jouvin** [comment]
In fact, playing a little bit more with this value, it seems less magic than I thought: it just resolves to `localhost` and this is not making services like Apache very happy... Feel free to close this issue if you don't think this is a useful addition.

**Comment by stdweird** [comment]
`HOSTNAME` is defined by either joining `hostname` and `domain` or `realhostname`. `realhostname` supports fqdn, so you could use that.
