### ISSUE TITLE
ncm-accounts: add the possibility to add or replace group members

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#658]
I encountered a use case that `ncm-accounts` cannot handle currently. Our web servers run `httpd` with a non default user (defined by Apache `User` directive) and a non default group (defined by Apache `Group` directive). Unfortunately this is causing troubles with the new `cgid` used to run CGIs when using a multithreaded MPM (Apache 2.4): in this case the httpd child must access a named socket (file) located under `/var/run/httpd` which is readable only by `root` and the group `apache` (whatever Apache `Group` directive is set to). As `/var/run/httpd` is recreated at each boot, using Quattor `ncm-dirperm` to change directory group is not working well on machines (like VMs) where you don't necessarily start `ncm-cdispd`.
An easier approach would be just to add the user used to run Apache in the local `apache` group. Unfortunately, the current `ncm-accounts` only allows to replace the group member list (which should not be a problem in this particular case as the group has no explicit members): it would help to address the general case to be able to say that group members should be added to existing ones instead. Looking quickly at `ncm-accounts`, I have the feeling that this would be a minor modification. Is there an agreement on doing it?

**Comment by jouvin** [comment]
In fact, looking again at `ncm-accounts`, I realize that currently this configuration module doesn't allow to define the list of group members but only the group gid. Thus I changed the title.
I am not sure why this restriction, may be this is only that we didn't implement it... The change would really be trivial: just add to `apply_profile_groups()` the processing of `$cfg->{members}` after adding this property to the schema.
Any objection?

**Comment by stdweird** [comment]
what is wrong with adding the apache group to the list of groups of this user? (or is this a user created by rpm/something else?) i guess the main issue is that there would be a second way to add users to the group, possibly leading to unexpected results. maybe by adding a a restriction to the schema that only `kept_users` can be added this way?

**Comment by jouvin** [comment]
Yes, in my use case, the account is in LDAP and there is no reason for it to have this group by default... I need to double check how members are added to groups. Clearly it should not break what exists today!

**Comment by stdweird** [comment]
hmm, interesting. so `ncm-accounts` requires a working ldap config.
what creates the socket?
also, if httpd is not running as apache user, have you tried also changing the user in the unitfile (it will probbaly create /var/run/httpd with correct ownership)

**Comment by jouvin** [comment]
I don't see any documented way of customizing the group for the `/var/run/httpd` directory. Are you aware of something?

**Comment by stdweird** [comment]
it's not about customising the directory, it's about running httpd unit as another user 
```
mkdir /etc/systemd/system/httpd.conf.d/

cat /etc/systemd/system/httpd.conf.d/differentuser.conf > <<EOF
[Service]
User=userx
Group=groupy
EOF
```

if this works, you can configure it with quattor with https://github.com/quattor/configuration-modules-core/pull/615

**Comment by jouvin** [comment]
Thanks, I'll try to have a look. I didn't manage to find this information... Anyway, the proposed extension to `ncm-accounts` can be useful for addressing corner cases and should not change anything to the current behaviour, just add a new possibility.
