### ISSUE TITLE
ncm-metaconfig: logging insufficient

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#664]
At info level, `metaconfig` reports nothing about what it has done (modified files, restarted services). This makes troubleshooting difficult. My proposal is:
- Promote from verbose to info the message about service action being done
- When closing the file, check if it was modified and in this case log at info level the name of modified file.

**Comment by stdweird** [comment]
see https://github.com/quattor/CAF/pull/117 and ref to the ncm-ncd PR in it. to track any `CAF::Service` related events is trivial to add.
i do not think this should be a per component issue

**Comment by jouvin** [comment]
I did the suggested mods before seing your remarks! Probably part of the logging could be done in CAF but until we agree on what must be done in CAF and it is implemented, it would be useful to have a little bit of information about what `metaconfig` has changed on the system. The PR also includes a bit of cleanup in the unit tests and a few minor fixes (like messages between `''` preventing variablei interpolation).
