### ISSUE TITLE
ncm-systemd: error caused by legacy service off

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#686]
On VMs with image managed by Quattor, we disable (set to off) `cdp-listend` and `ncm-cdispd` services. I saw that this was causing errors when running `ncm-systemd` (EL7, in the example below `ncm-cdispd` is off):
```
[INFO] running component: chkconfig
---------------------------------------------------------
updated /var/run/quattor-components/chkconfig
[WARN] Found current unit cdp-listend.service via Chkconfig but is not in Unit. (This is unexpected, please notify the developers)
[ERROR] get_unit_show: no alias for unit cdp-listend.service defined. (Forgot to update cache?)
[ERROR] get_unit_show: no alias for unit cdp-listend.service defined. (Forgot to update cache?)
[ERROR] is_active no ActiveState for unit cdp-listend.service found.
[ERROR] systemctl_command_units /usr/bin/systemctl start -- fetch-crl-boot.service returned ec 256 and output Job for fetch-crl-boot.service failed because the control process exited with error code. See "systemctl status fetch-crl-boot.service" and "journalctl -xe" for details.

[INFO] configure on component chkconfig executed, 4 errors, 1 warnings
updated /var/run/quattor-components/chkconfig
```

Doing a `chkconfig --level 345 xxx on` is enough to fix the problem. IMO, this is an unexpected behaviour...

**Comment by stdweird** [comment]
this looks like some variation of the previous issue.
can you send me `--debug 5` output, and output of `systemctl show cdp-listend.service`?

**Comment by jouvin** [comment]
Here they are. The disabled component is `cdp-listend`.

[cdp-listend.txt](https://github.com/quattor/configuration-modules-core/files/92937/cdp-listend.txt)
[debug.txt](https://github.com/quattor/configuration-modules-core/files/92938/debug.txt)

**Comment by stdweird** [comment]
@jouvin can you also give
```bash
systemctl --full --all list-units |grep cdp-listend
systemctl --full --all list-unit-files |grep cdp-listend
```

this looks like a variation of the issue before, i think i already found the bug.

**Comment by jouvin** [comment]
On a machine exhibiting the problem both commands returns nothing. On a machine where `cdp-listend` is on, the output is:
```
[root@tracsrv2 ~]# systemctl --full --all list-units |grep cdp-listend
  cdp-listend.service                                                                                  
          loaded    active   running   SYSV: cdp-listend daemon for the CDP notifications
[root@tracsrv2 ~]# systemctl --full --all list-unit-files |grep cdp-listend
```

**Comment by stdweird** [comment]
@jouvin thx, i suspected as much. can you try https://github.com/quattor/configuration-modules-core/pull/687?

**Comment by jouvin** [comment]
I'll try but probably not before this afternoon...
