### ISSUE TITLE
remove 'local *DTA'

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#692]
some of the components have a 
```perl
local(*DTA);
```
statement, but i have no clue why it's there or what it does (`DTA` is not used anyewhere else and only used in this way). googling for `DTA` revealed nothing, so i don't think it's a perlism.

we also have components that do not have this (and work fine), so i'm inclined to remove this unless someone knows something more.

**Comment by jouvin** [comment]
As for me, I always accepted it as a perlism! I have not clue about what it does and if you don't too, I'm also inclined to think that we can live without!

**Comment by jouvin** [comment]
Probably you could assign this issue to 16.4 if you want it to be discussed at the workshop. I hope 16.2 will be release before!
