### ISSUE TITLE
ncm-spma: yum schema does not support gpgkey option

### ISSUE THREAD

**Issue by drossy** [quattor/configuration-modules-core#717]
The yum schema has support for the gpgcheck option to check GPG signatures on packages but does not support the gpgkey option to allow per repository gpg keys - we sign our locally built rpms and have a seperate repository for them and it would be good to be able to specify the key in quattor

**Comment by jrha** [comment]
:disappointed: thanks for reporting this

**Comment by stdweird** [comment]
@jrha maybe in rc3 :smile:

**Comment by jrha** [comment]
:laughing:
