### ISSUE TITLE
Provide access to file-editor

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#720]
@jouvin has been working on a generic file editor for his [dpm work](https://github.com/quattor/configuration-modules-grid/pull/89), this should be made more generally usable as discussed in #699.

**Comment by jrha** [comment]
Perhaps in a new component?

**Comment by jouvin** [comment]
Done in https://github.com/quattor/CAF/pull/151.

**Comment by apdibbo** [comment]
Did the pull request above actually resolve what this was asking for?

**Comment by ned21** [comment]
See discussion in #699. @jouvin is going to take a look at exposing this either as a new component, or extending metaconfig to support it.
