### ISSUE TITLE
ncm-sysctl: /etc/sysctl.conf takes precedence over sysctl.d

### ISSUE THREAD

**Issue by ned21** [quattor/configuration-modules-core#737]
As per [this post](https://lists.fedoraproject.org/pipermail/devel/2012-March/164069.html) any OS vendor defaults shipped in /etc/sysctl.conf cannot be overridden in sysctl.d. The easy fix is to blank the file, either as part of ncm-sysctl, or by configuring another component (ncm-filecopy?) to do so. However it may be important to preserve any vendor supplied defaults which vary from the kernel defaults, e.g. by copying them to /etc/sysctl.d/00-defaults.conf

**Comment by jrha** [comment]
This was discussed briefly at the 21st workshop and agreed as a good idea.

**Comment by wdpypere** [comment]
for reference, on EL7 there is a symlink:
```
[root@node sysctl.d]# ls -l
lrwxrwxrwx 1 root root 14 Jan 29 09:03 99-sysctl.conf -> ../sysctl.conf
```

**Comment by jouvin** [comment]
According to discussion at April 2018 workshop, it seems easy to fix on EL7 by adding a Quattor-generated file as 991 or something that will be read after 99. It seems more difficult to find a clean solution on EL6 where `/etc/sysctl.cong`  is always read last.... May be ensure that the component is writing to this file, replacing the value if the key exists already. 
BTW, we need a schema refinement to allow to say that the value specified should be a 'final` value (overriding any default, including the system ones) or a default one that can be overriden by `/etc/sysctl.conf`.

**Comment by stdweird** [comment]
i want to add here that when `/etc/sysctl.conf` is managed by the compoent, it works as a fileeditor; so you can modify vendor values in el6 (but probably only once).

**Comment by ned21** [comment]
Since there's now a workaround for RH7 (use a file called 991-something), and in practice it's never really caught us out on RH5 & 6, closing this out.
