### ISSUE TITLE
ncm-ceph: allow control over deploying admin keyrings along with ceph.conf

### ISSUE THREAD

**Issue by gvasilak** [quattor/configuration-modules-core#742]
Currently, ncm-ceph runs `ceph-deploy admin` when pushing configuration files out to nodes. This means everything gets admin rights over the whole cluster, which is not always desired.

We should have a way to control whether it does `ceph-deploy admin` or `ceph-deploy push`.

@kwaegema suggested we use a list of nodes that get admin keyrings; all other nodes get just the configuration file. If the list is not defined we default to the previous behaviour.

**Comment by kwaegema** [comment]
The list is the easiest to do without breaking current behaviour. 
Since you volunteered to do this :smile:  The easiest way to achieve this is by passing this to the gvalues variable, and evaluate this before running write_and_push, or pass the conditional to this function.

**Comment by gvasilak** [comment]
I think we should eventually break current behaviour and default to not putting admin keyrings on everything. But for now, let's keep it this way and make the change gradual. Introduce the mechanism with the list first and then see about changing the defaults further down the line.

**Comment by kwaegema** [comment]
fixed by #1230 
the new version of component will only make mon nodes admin nodes
