### ISSUE TITLE
ncm-ceph: check admin keyring is current before running ceph-deploy admin

### ISSUE THREAD

**Issue by gvasilak** [quattor/configuration-modules-core#743]
Currently, ncm-ceph runs `ceph-deploy admin` which `scp`s the admin keyring out of `/home/ceph` to all machines it touches.

The keyring is put there by running `ceph-deploy gatherkeys` which is run every time; it looks for the key in `/home/ceph` and fetches it from another node if it's not there. The problem is this file stays there and if it becomes out-of-date (say by redefining the `key` field of the keyring) `ceph-deploy admin` will blindly push it out to all nodes rendering them unable to run any commands as the admin user.

I propose we introduce a simple check for the validity of this file. Presumably, the deployhost (from where this is run) does have an admin keyring in its `/etc/ceph` directory; we should check if this is different from the one in `/home/ceph` and assume it is the one that's valid. If the files differ the one in the ceph user's home directory should be replaced by the one in `/etc/ceph`.

**Comment by kwaegema** [comment]
fixed by #1230
