### ISSUE TITLE
ncm-opennebula: Include OneFlow support

### ISSUE THREAD

**Issue by alvarosimon** [quattor/configuration-modules-core#755]
At this moment `oneflow-server.conf` file is provided as a default conf file from  OneFlow package. We should manage this conf file from Quattor as we did for `oned.conf`and `sunstone-server.con` services, to change for example these default values:

>:host: 127.0.0.1
>:port: 2474

**Comment by jrha** [comment]
@alvarosimon any idea when this can be done by? I don't like bumping milestones, I'd rather just leave it unassigned if it's not a priority!

**Comment by alvarosimon** [comment]
Ah... I forgot about it, this is not a priority at this moment but it could quite easy to implement, I can submit a PR next week and wait for @stdweird review after his holidays.

**Comment by jrha** [comment]
Okay, thanks!
