### ISSUE TITLE
ncm-named: Options not correctly passed through to resolv.conf

### ISSUE THREAD

**Issue by drossy** [quattor/configuration-modules-core#763]
When I add a line like

`"/software/components/named/options" = list('timeout:2');`

to my quattor configuration, the JSON appears to be correctly created:

      "named": {
        "active": true,
        "dependencies": {
          "pre": [
            "spma"
          ]
        },
        "dispatch": true,
        "options": [
          "timeout:2"
        ],

However when the component runs the entry added to resolv.conf is 

`options ARRAY(0x1aadb48)`

whereas I'd expect it to be 

`options timeout:2`

I'm using version 15.2.0 on RHEL 6.7

**Comment by jrha** [comment]
Does `ncm-resolver` work correctly?
I note that we agreed to deprecate and remove support for `resolv.conf` from `ncm-named` some time ago.
