### ISSUE TITLE
ncm-sudo: missing elements in list of STRING_OPTS in sudo.pm

### ISSUE THREAD

**Issue by brunocanning** [quattor/configuration-modules-core#773]
The parameters `secure_path` and `mailsub` are present in `ncm-sudo/src/main/pan/components/sudo/schema.pan` but are not present in the list of `STRING_OPTS` in `ncm-sudo/src/main/perl/sudo.pm` (line 90). Therefore, when defining a value for either parameter, ncm-sudo cannot write values for these keys, so the visudo check fails and the new configuration in /etc/sudoers does not get written.

* Component version: 16.2.0
* OS: Scientific Linux, version: 6x-x86_64
* Steps required to reproduce the problem:
  * Add a line like this to your sudo configuration:
`'/software/components/sudo/general_options/options' = dict('secure_path', '/sbin:/bin:/usr/sbin:/usr/bin');`
  * Compile a host profile that will contain this configuration and let the host receive it.

* Actual result:
  * Component errs with message:
> 2016/05/18-17:10:48 -----------------------------------------------------------
> 2016/05/18-17:10:48 [ERROR] sudoers check said: visudo: >>> /proc/self/fd/0: syntax error near line 19
> 2016/05/18-17:10:48 [ERROR] Invalid sudoers file. Not saving
> 2016/05/18-17:10:48 [INFO] configure on component sudo executed, 2 errors, 0 warnings

  * Configuration line does not get written into /etc/sudoers

* Expected result:
  * Component runs without error.
  * This line: `Defaults        secure_path=/sbin:/bin:/usr/sbin:/usr/bin` gets written into /etc/sudoers.

**Comment by brunocanning** [comment]
I tried adding `secure_path` to the list of `STRING_OPTS` in `/usr/lib/perl/NCM/Component/sudo.pm` on the test host and the component now runs without error. I'm starting with a discussion here but I can upgrade to a pull request if everyone is happy with this. The parameter `secure_path` was added to the schema in order to fix issue #281, but I can't find a PR for the corresponding change to the perl code.

**Comment by stdweird** [comment]
@brunocanning first thing to check is to see if all current options  (BOOLEAN_OPTS, ...) in those list match the pan type (boolean, ...). if they do, it's pretty easy to get rid of the lists (as you can actually access the type from perl).
as this is a filewriter and string generation, most of code should be moved to TT, but that might be a bit out of scope :smile:

**Comment by brunocanning** [comment]
@stdweird sorry, forgot to say, `BOOLEAN_OPTS` and `INT_OPTS` are complete and in the same order as the schema. Yes, would be nice to move to TT but this looks like an easy win to me. Ready for a PR?

**Comment by stdweird** [comment]
sure, but should be cleaned-up  / rewritten. code is very old and looks unneccesarily complicated

**Comment by brunocanning** [comment]
Code merged from pr #796, closing issue.
