### ISSUE TITLE
ncm-resolver/ncm-named: Lengths of lists should be validated

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#785]
Both ncm-resolver and ncm-named can configure a list of name-servers in `resolv.conf` (although we agreed in #434 to deprecate this feature of ncm-named).

The man pages and source code for the GNU resolver state that:
> Up to MAXNS (**currently 3**, see &lt;resolv.h&gt;) name servers may be listed, one  per  keyword.
```c
# define MAXNS	3	/* max # name servers we'll track */
```

The documentation for Solaris agrees:
> Succeeding lines list the IP addresses of up to three DNS master, secondary, or cache-only name servers that the resolver should consult to resolve queries. (Do not list **more than three** primary or secondary servers.)

Therefore I propose limiting the length of the `servers` property to 3.

**Comment by stdweird** [comment]
there's a similar limit for the `search` field. i think there is 5 or so (and yes, we ran into the limit once :smile: )

**Comment by jrha** [comment]
> The search list is currently limited to six domains with a total of 256 characters.
