### ISSUE TITLE
ncm-spma 16.6.0-rc1: upgrade fails due to an (unexisting) conflict with another yum instance

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#800]
I've the feeling that the new `ncm-spma` in 16.6.0-rc1 is broken (https://github.com/quattor/release/issues/249). Trying to upgrade Quattor to this version on a real machines (several different ones with different profiles, all running SL6), it fails with an error about another yum instance running at the same time... except that this instance doesn't exist and is probably what is forked by `ncm-spma`... I attach the `ncm-spma` log for more details. All the runs resulting in errors correspond to the 16.6.0-rc1 ncm-spma version. I open the issue against `ncm-spma` but there is a possibility that this is something that changed with `ncm-ncd` locking resulting in several `ncm-ncd` running at the same time because of the `ncm-cdispd` restart during the Quattor package upgrade.

[spma_logs.zip](https://github.com/quattor/configuration-modules-core/files/349748/spma_logs.zip)

**Comment by stdweird** [comment]
i don't think this is a bug in spma. the logs clearly show another yum running, someting whcih is not managed by spma, but by yum.
if no yum was running while yum tought there was, then there is a serious issue elsewhere.

if ncm-ncd does not take a lock, that's eally bad. can you add 
debug =5 
to /etc/ncm-ncd.conf
on a machine that hasn't been updated (and hope it runs into the same stuff). it should give a better idea what goes wrong

**Comment by jouvin** [comment]
@stdweird I opened the issue here but as I said I am also almost convinced that the problem is in fact in `ncm-ncd` that lead to several yum instance running at the same time. I'll try to produce the debug log later today...

**Comment by stdweird** [comment]
actually i think that the new CAF::Lock is not compatible with the old one (ie lock taken by ncm-ncd before update is not seen as lock by ncm-ncd running with updated CAF). it would explain why we never saw this, as we have updated perl-CAF without updating ncm-ncd.

if it's easy to reproduce, you should be able to make it work by doing
```
yum clean all -y
yum install perl-CAF -y
ccm-fetch 
ncm-ncd --co -all
```

relevant PR is https://github.com/quattor/CAF/pull/132

**Comment by jouvin** [comment]
@stdweird looks as a reasonable explanation... I'll try your suggested commands to validate it. But this is clearly not an acceptable workaround for 1K machines!

**Comment by stdweird** [comment]
ofcourse not, we could revert the CAF::Lock PR and wait for a patch to support the compatibility

**Comment by jouvin** [comment]
It clearly seems to be a locking issue in `ncm-ncd`. This can be seen with 2 start lines in `ncm-spma` log without an end line in-between. And looking at the process on the machine:
```
[root@grid63 ~]# ps -e -Oppid|grep yum                                                                                                                                     
2190051 2190010 D ?        00:01:10 /usr/bin/python /usr/bin/yum -c /etc/yum.conf -y distro-sync
2192528 2192519 S ?        00:00:00 /usr/bin/python -tt /usr/sbin/yum-complete-transaction -c /etc/yum.conf -y
2193868 2190024 S pts/1    00:00:00 grep yum
[root@grid63 ~]# tail -f /var/log/ncm/component-spma.log                                                                                                            
2016/07/06-14:46:02 -----------------------------------------------------------
2016/07/06-14:47:42 [INFO] configure on component spma executed, 0 errors, 0 warnings
2016/07/06-14:47:42 [INFO] EVENT: spma modified file /etc/yum.quattor.repos.d/quattor_15.12.0.repo
2016/07/06-14:47:42 [INFO] EVENT: spma modified file /etc/yum.quattor.repos.d/quattor_15.12.0.pkgs
2016/07/06-14:47:42 [INFO] EVENT: spma modified file /etc/yum/pluginconf.d/versionlock.list
2016/07/06-14:48:04 [INFO] configure on component spma executed, 0 errors, 0 warnings
2016/07/06-14:48:39 -----------------------------------------------------------
2016/07/06-14:49:56 [INFO] configure on component spma executed, 0 errors, 0 warnings
2016/07/06-15:28:31 -----------------------------------------------------------
2016/07/06-15:30:07 -----------------------------------------------------------
^C
[root@grid63 ~]# ps -e -Oppid|grep yum                                                                                                                   
2190051 2190010 D ?        00:01:11 /usr/bin/python /usr/bin/yum -c /etc/yum.conf -y distro-sync
2192528 2192519 S ?        00:00:00 /usr/bin/python -tt /usr/sbin/yum-complete-transaction -c /etc/yum.conf -y
2194911 2190024 S pts/1    00:00:00 grep yum
[root@grid63 ~]# rpm -q perl-CAF
perl-CAF-16.6.0-rc1_1.noarch
[root@grid63 ~]# ps -p 2190010
    PID TTY          TIME CMD
2190010 ?        00:00:00 ncm-ncd
[root@grid63 ~]# ps -p 2192519
    PID TTY          TIME CMD
2192519 ?        00:00:00 ncm-ncd
[root@grid63 ~]# ps -e|grep ncm-ncd
2190010 ?        00:00:00 ncm-ncd
2192519 ?        00:00:00 ncm-ncd
2193755 ?        00:00:00 ncm-ncd
```
So you can see the 2 yum instances with different `ncm-ncd` parents... (during the upgrade this is expected to have 3 `ncm-ncd` instances started, 2 waiting for the first one to complete).

Unfortunately, the suggested commands don't help despite all the RPMs are 16.6.0-rc1:
```
[root@grid63 ~]# rpm -q ncm-ncd perl-CAF ncm-spma
ncm-ncd-16.6.0-rc1_1.noarch
perl-CAF-16.6.0-rc1_1.noarch
ncm-spma-16.6.0-rc1_1.noarch
```
This looks like if the new CAF locking module is broken rather than incompatible with the old one...

May be this is better to close this issue and reopen it in perl-CAF....

**Comment by stdweird** [comment]
https://github.com/quattor/CAF/issues/172

**Comment by jouvin** [comment]
Issue closed as, even though the problem has been identified with `ncm-spma`, it is a victim and the real issue seems to be `perl-CAF`.
