### ISSUE TITLE
ncm-spma 16.6.0-rc1: 3rd update_pkgs with userpkgs=false failed

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#801]
After fixing the `CAF::Lock` problem (https://github.com/quattor/CAF/issues/173), any attempt to run SPMA after Quattor upgrade results in an error (output is when run verbose):
```
[VERB] Executing command: repoquery -c /etc/yum.conf -C -l -g --grouppkgs mandatory,default names
[VERB] Command options: stderr=SCALAR(0x4009fb0) stdout=SCALAR(0x400a268)
[VERB] Group expansion output: 
[ERROR] userpkgs_retry: 3rd update_pkgs with userpkgs=false failed.
```
I don't think this is related to the locking problem, this is why I open a new issue. May it be related to the the new `groups/names` defined as an empty dict? (https://github.com/quattor/configuration-modules-core/pull/798).

This is a showstopper for 16.6.0 release (https://github.com/quattor/release/issues/249).

**Comment by stdweird** [comment]
@jouvin do you have any groups set before? (either explicitly or implicitly via schema defaults)
can you also add the output of `--debug 5` to make sure there's nothing else going wrong

**Comment by jouvin** [comment]
Here is my group config returned by the nice `ccm` command:
```
[root@grid63 ~]# ccm /software/groups
updated /var/lib/ccm/profile.1311/ccm-active-profile.1311-2559207.writetest
updated /var/lib/ccm/profile.1311/ccm-active-profile.1311-2559207
+-/software/groups
  +-names
    $ default : true
    $ mandatory : true
    $ optional : false

```
and `ncm-spma` output with debug=5 is (relevant part):
```
[VERB] Executing command: repoquery -c /etc/yum.conf -C -l -g --grouppkgs mandatory,default names
[VERB] Command options: stderr=SCALAR(0x2758d10) stdout=SCALAR(0x2758fc8)
[VERB] Group expansion output: 
[ERROR] userpkgs_retry: 3rd update_pkgs with userpkgs=false failed.
[INFO] configure on component spma executed, 1 errors, 0 warnings
[VERB] No events to report
[VERB] set_state for component spma /var/run/quattor-components/spma (msg 1)
[VERB] Opening file /var/run/quattor-components/spma
[VERB] Changes to /var/run/quattor-components/spma:
```
The values for `/software/groups/names` are the default ones enforced by the schema. If I revert this to the previous version used on the machine (15.12), `/software/groups` is an empty dict. I'm trying the chase the change, probably in `config-rpm` as the default value in the schema has been there for a while (several years).

**Comment by jouvin** [comment]
I'd suggest a RC2 to be sure that I have all the proper fixes for the various issues found in RC1. I have the feeling I did what was proposed by @jrha to fix the `/software/groups` problem seen in RC1 but I may have done something wrong...

**Comment by jouvin** [comment]
In fact there is nothing wrong in `ncm-spma` code itself but I made a mistake when copying #798 changes to my local install (cleared `groups/names` instead of `groups` springing into existence a group called `names`). Sorry for the noise.
