### ISSUE TITLE
ncm-spma doesn't handle properly group names with embedded spaces

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#812]
A YUM group name can be made of multiple words (a string with spaces). This is not handled properly by `ncm-spma`. In addition, if the group name is incorrect (the group doesn't exist), the error logged is difficult to interpret (no explicit error logged).

**Comment by jrha** [comment]
I'd like this to be discussed more before accepting it, so I'm pushing it back until you return from holiday.

**Comment by jrha** [comment]
We agreed at the workshop to deprecate and remove support for yum groups as they can lead to dependency creep, so this is probably a wontfix.
