### ISSUE TITLE
ncm-network: add a hook to allow running of an extra config script after an interface is reconfigured

### ISSUE THREAD

**Issue by ned21** [quattor/configuration-modules-core#814]
When configuration of a network interface changes, ncm-network uses ifdown/ifup to activate the changes. However this means multipath routes set up via another script (e.g. /etc/init.d/rc.routing) are lost. ncm-network should be extended to run an user script (rc.routing in this case) whenever an interface is reconfigured.

**Comment by stdweird** [comment]
what OS version is this? (recent) el6 and el7 have a `/etc/sysconfig/network-scripts/ifup-post` which ends with
```
if [ -x /sbin/ifup-local ]; then
    /sbin/ifup-local ${DEVICE}
fi
```
which you could use to trigger anything you want.
(and what are multipath routes? it's probably something shorewall can setup for you)

**Comment by ned21** [comment]
That is present on RH5 too. I will check internally to find out why we are not using it.

**Comment by ned21** [comment]
/sbin/ifup-local looks sufficient.
