### ISSUE TITLE
ncm-afsclt fails if cache size is set to AUTOMATIC

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#815]
`nfs-afsclt`, since changes introduced in Dec. 2015 (ca8692b8c787da2dd80d21f1e174011c7831a13b), fails if the cache size is set to AUTOMATIC when parsing the existing `cacheinfo` file and when doing some sanity checks on the size.

Should be considered as a showstopper for [16.6.0-rc4](https://github.com/quattor/release/issues/253) (missed at LAL in 16.2 in fact as we didn't deploy 16.2).

**Comment by jrha** [comment]
quattor/release#253
