### ISSUE TITLE
ncm-opennebula : creation of vnet with OpenNebula 5

### ISSUE THREAD

**Issue by StephaneGerardVUB** [quattor/configuration-modules-core#819]
I have tested creation of a vnet with ncm-opennebula 16.2.0-1 and it fails with the following error message :
No VN_MAD in template for Virtual Network.
According to the documentation of ONE5 :
http://docs.opennebula.org/5.0/operation/references/vnet_template.html
the VN_MAD attribute is mandatory.
The problem doesn't seem to be fixed by the release 16.6.0-rc5.

**Comment by alvarosimon** [comment]
Hi @StephaneGerardVUB 

Yes you are right, also oned has been changed in ONE 5.0 #784, we hope to include this in a new PR asap. Unfortunately these changes are not ready to be included into 16.6.0, maybe in the next release...
btw aii-opennebula will fail as well if you use the new OpenNebula version, the boot section is different, I hope to include these changes soon as well...

**Comment by alvarosimon** [comment]
@StephaneGerardVUB the new PR should fix this issue #824 
also @stdweird has created a new `Net::OpenNebula` version to fix the opennebula v5 hypervisors allocation.
I'm testing it right now in altaria.
