### ISSUE TITLE
ncm-metaconfig beats: Schema prevents multiple outputs being used.

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#825]
The schema currently specifies that one and only one output may be used, which is not a restriction in filebeat, was this intentional?

```pan
type beats_output = {
    'elasticsearch' ? beats_output_elasticsearch
    'logstash' ? beats_output_logstash
    'file' ? beats_output_file
    'console' ? beats_output_console
} with length(SELF) == 1;
```

The message displayed when this validation fails is also very user-unfriendly
```
[panc] user-defined validation failed
[panc] element path: '/software/components/metaconfig/services/_2fetc_2ffilebeat_2ffilebeat_2eyml/contents/output'
```

Any reason not to change this to the following?
```pan
type beats_output = {
    'elasticsearch' ? beats_output_elasticsearch
    'logstash' ? beats_output_logstash
    'file' ? beats_output_file
    'console' ? beats_output_console
} with {
    length(SELF) >= 1 || error('At least one beat output must be specified')
};
```

**Comment by stdweird** [comment]
@jrha i do not recall. maybe older versions had this restriction? if you confirm that multiple versions work and which version you use, i'll make the PR.

**Comment by jrha** [comment]
Using both logstash and file is working fine with filebeat version 1.2.3.
