### ISSUE TITLE
ncm-download: disclaimer in schema

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#831]
`ncm-download` has an additional disclaimer wrt liability in the schema https://github.com/quattor/configuration-modules-core/blob/master/ncm-download/src/main/pan/components/download/schema.pan#L6

if this disclaimer is really needed (in the schema of all places), i would rather move it in a template in `maven-tools`, in case it is required elsewhere.
if not, i would like to remove it. (i'm doing some cleanup and try to add support for nss based certificates in curl)

**Comment by stdweird** [comment]
@ned21 @gombasg this is some MS requirement i guess?

**Comment by stdweird** [comment]
actually, this seems implied by clause 8 (and 9) of the apache 2.0 license http://www.apache.org/licenses/LICENSE-2.0#no-liability (i'm no legal expert, but the phrasing looks similar).

**Comment by ned21** [comment]
I think there was some confusion in the early days and a lot of our internal components had this in every file. It was later clarified this was not necessary and the terms of the licence means you are free to remove it anyway.

**Comment by stdweird** [comment]
@ned21 thanks for clarifying. wrt ncm-download, this was removed in https://github.com/quattor/configuration-modules-core/pull/833/commits/650d3f2dc09e7b834517aa3fee075a233f71d9de
