### ISSUE TITLE
ncm-metaconfig: ccm.contents can't be a list

### ISSUE THREAD

**Issue by kwaegema** [quattor/configuration-modules-core#850]
when I use this is mij tt file: 
[% CCM.contents.join("\n") -%]

I get some not a Hash reference error (CCM.contents is here indeed a list)

```
# INFO BEGIN test for Base test for slaves config
# VERBOSE Set eol to 0
# VERBOSE Using includepath /home/kwaegema/gitrepos/configuration-modules-core/ncm-metaconfig/src/main
# VERBOSE Using relpath 'metaconfig'
# DEBUG: 3 Using Template::Toolkit to render module hdfs/list
# DEBUG: 3 Contents is a Element instance
# DEBUG: 3 We must ensure that all templates lie below /home/kwaegema/gitrepos/configuration-modules-core/ncm-metaconfig/src/main.
# VERBOSE Using template metaconfig/hdfs/list.tt for module hdfs/list
Not a HASH reference at /usr/lib64/perl5/vendor_perl/Template/Service.pm line 76.
```

**Comment by stdweird** [comment]
@kwaegema what CCM version is this? https://github.com/quattor/CCM/pull/90 should have fixed this. i assumed you were running this on one of our nodes, so i thought CCM was recent enough. updating to 16.6 should do the trick

**Comment by ned21** [comment]
@kwaegema - can you confirm if this is still present in 16.6 please?

**Comment by jrha** [comment]
@kwaegema any news?

**Comment by kwaegema** [comment]
@stdweird @ned21 @jrha updated to 16.6, this works, thanks!
