### ISSUE TITLE
ncm-network: hostname is not set in el7

### ISSUE THREAD

**Issue by rhumroux** [quattor/configuration-modules-core#870]
In el7, hostname should be set through either:
-  **/etc/hostname** [requires reboot] 
-  **hostnamectl set-hostname --static MYHOSTNAME** [requires restart of hostnamed].

Right now, it means the hostname applied is the one from **ks**. This poses problems when you install through private network, but want a public hostname.
One service particularly affected is cdp-listend, which listens on the hostname ip, which can be in some cases different from the one notified.

**Comment by stdweird** [comment]
can you share the `/system` of this node? `/etc/hostname` looks like the obvious thing to set, probably  already in `aii-ks`. 
but why do you need this? you cannot have a private node with public IP? (what service are you trying to configure?)

**Comment by rhumroux** [comment]
To be more precise, what does not work anymore is putting **HOSTNAME=** in `/etc/sysconfig/network` [here](https://github.com/quattor/configuration-modules-core/blob/master/ncm-network/src/main/perl/network.pm#L631-L636) in the code.

The code concatenates /system/network/hostname & /system/network/domainname, or takes /system/network/realdomainname if defined . Setting those 2(3) is now having no effect. Putting this in the ks would work when installing, but not if you want to change it afterwards.

I think to do it properly, `/etc/hostname` should be set in the ks, and **hostnamectl** command could be used in ncm-network component.

To answer your question, we are installing all nodes using a private domain, and where relying on `/system/network` to change the hostname to public in some cases.That brings us a lot of problems [fixed by a filecopy of `/etc/hostname` for now].

**Comment by stdweird** [comment]
@rhumroux that's odd. wrt setting `/etc/hostname`, i assume you wan this before `ks-post-install` runs, so the post install happens with the correct name?
supporting `hostnamectl ` is definitely for a different PR, supporitng "live" modification of hostname without reboot is new feature, will need plenty of testing.

but can you send me a template with aii using a different hostname? do you just set the boot nic to a private nic?

**Comment by rhumroux** [comment]
@stdweird yes, it would be best to put it before `ks-post-install`.
I think the ncm-network component already changes the hostname "live": changing **HOSTNAME=** in `/etc/sysconfig/network` and restarting the network already changes the hostname, doesn't it ? But that's another issue.

The ks has the following line:
`network --bootproto=static --device=eth0 --hostname=vm111.iihe.ac.be`
and as you guessed, eth0 is the boot nic and is private. It seems having --hostname option here is inefficient too ...

**Comment by stdweird** [comment]
@rhumroux thanks (and for the /system dump). it would also help a bit if you had a diff a original ks file and a handcrafted one that works correctly.

**Comment by stdweird** [comment]
@rhumroux can you restate the remark wrt `--hostname`: is it sufficient or not to fix this issue (would certainly be the easiest way to fix it)

**Comment by rhumroux** [comment]
@stdweird : I don't have a modified ks (I fixed it with an ugly filecopy after install). To answer about `--hostname` in the ks, writing the hostname in `/etc/hostname` durign pre-install should fix the issue when installing, and should work for our case.

But then one would have to remember that you can't change the hostname after install. as the network component, which used to do that, can't do it anymore ...

**Comment by stdweird** [comment]
@rhumroux my question is the following: the kickstart with static ip (which you seemed to use), has a line 
```
network ... --hostname a.b.c
```
with `a.b.c` the hostname you want.

does this set the correct hostname (without any other modification).
if it doesn't the `--hostname` option for network in kickstart is broken.

if you didn't use static network (i.e. dhcp) in aii, the `--hostname` is not set in kickstart, so it's normal the hostname is the wrong one in your case.
