### ISSUE TITLE
ncm-metaconfig beats: Numeric values rendered with quotes

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#915]
I'm not sure whether this is a `metaconfig` or a` CAF::TextRender` problem, but we spotted this when filebeat got updated and no longer parsed the stringified value.

The file output has a property called `rotate_every_kb` which is defined in the schema as `long(0..)` and assigned the value `1000000`, however when rendered it gets quoted:

```yaml
output:
  file:
    path: /tmp/filebeat
    rotate_every_kb: '1000000'
```

At first I thought this might be the way `YAML::XS` serialises hashrefs, but the following renders correctly:

```perl
use YAML::XS;

print Dump {
    output => {
        file => {
            path => '/tmp/filebeat',
            rotate_every_kb => 1000000,
        },
    },
};
```

:confused:

Observed with ncm-metaconfig 16.2.0 on SL 6.7

**Comment by stdweird** [comment]
are you using `json_typed 1` in `ccm.conf`? if not, this is normal for json templates

**Comment by jrha** [comment]
I thought we had, but it seems we haven't!

**Comment by jrha** [comment]
Thanks, that did indeed fix it.

Doh.

**Comment by stdweird** [comment]
fyi, it's default in 16.8
