### ISSUE TITLE
ncm-systemd: Double space and root items on the bottom of generated unit files.

### ISSUE THREAD

**Issue by jnovy** [quattor/configuration-modules-core#939]
ncm-systemd generates the unit file in weird format, template example:

```
prefix "/software/components/systemd/unit/syslog-ng.service/file";

"only" = true;
"replace" = true;
"config" = dict(
        "unit", dict(
                "Description", "MS: LSB: syslog-ng is an alternative system logger",
                "After", list("network-online.target", "rc.afs.service"),
                "Requires", list("syslog.socket"),
        ),
        "service", dict(
                "Type", "forking",
                "ExecStart", "syslog-ng start",
                "ExecStop", "syslog-ng stop",
                "ExecReload", "syslog-ng reload",
        ),
        "install", dict(
                "Alias", list("syslog.service"),
                "WantedBy", list("multi-user.target"),
        ),
);
```

genrates the following unit file:

``` ini
[Install]
Alias=syslog.service
WantedBy=multi-user.target


[Service]
ExecReload=syslog-ng reload
ExecStart=syslog-ng start
ExecStop=syslog-ng stop
Type=forking

[Unit]
After=network-online.target
After=rc.afs.service

Description=MS: LSB: syslog-ng is an alternative system logger
Requires=syslog.socket
```

Problems:
1) newline on top of the file, why?
2) root vars like Description/Requires on bottom, should be on top
3) double newline between [Install] and [Service]

Environment:
ncm-systemd-16.8.0-1.noarch
Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Comment by stdweird** [comment]
The section names and the attributes within each section are sorted alphabetically.

I'll cleanup the spurious newlines. Not sure what this will trigger on the hosts though

**Comment by stdweird** [comment]
The section names and the attributes within each section are sorted alphabetically.

I'll cleanup the spurious newlines. Not sure what this will trigger on the hosts though

**Comment by stdweird** [comment]
The section names and the attributes within each section are sorted alphabetically.

I'll cleanup the spurious newlines. Not sure what this will trigger on the hosts though

**Comment by stdweird** [comment]
The section names and the attributes within each section are sorted alphabetically.

I'll cleanup the spurious newlines. Not sure what this will trigger on the hosts though

**Comment by stdweird** [comment]
The section names and the attributes within each section are sorted alphabetically.

I'll cleanup the spurious newlines. Not sure what this will trigger on the hosts though

**Comment by stdweird** [comment]
please don't mind the comments above. github and local network didn't like each other much.
