### ISSUE TITLE
ncm-yaim: Rpmlint fails

### ISSUE THREAD

**Issue by gvasilak** [quattor/configuration-modules-core#940]
`rpmlint` fails with the following error message:

> ncm-yaim.noarch: E: zero-length /usr/lib/ncm/config/yaim/empty

This was observed on SL7, running ncm-yaim 16.2.0 when running `build_all_repos.sh`.

Ensure the title of this issue starts with the component name followed by a colon, e.g.
> ncm-example: demonstrate what titles should look like

Describe the problem here.

If this is a bug report, remember to include:

* The version of the component you are using (rpm -q $component)
* What OS version you are using (/etc/redhat-release or similar)
* Steps required to reproduce the problem
* Actual result versus expected result

**Comment by jrha** [comment]
Will be fixed/removed in quattor/configuration-modules-grid#122
