### ISSUE TITLE
ncm-systemd: support systemd-resolved

### ISSUE THREAD

**Issue by ned21** [quattor/configuration-modules-core#941]
My colleague Adam asks if `systemd-resolved` can be supported to replace of `/etc/resolv.conf` for configuring DNS resolver?

**Comment by jrha** [comment]
If you really want to use it should read `/etc/resolv.conf` automagically (see https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#/etc/resolv.conf).

**Comment by stdweird** [comment]
@ned21 @ajf8 can you be a bit more specific?
do you want full control over `/etc/systemd/resolvd*`; or is generating `/etc/systemd/resolvd.conf.d/quattor.conf` enough?
and should it also manage `/etc/resolv.conf`?

**Comment by ned21** [comment]
The concern was around being able to ensure system doesn't override our configuration, with regards to DNS. We really don’t want to use the systemd resolver. I'm not certain, but don't think RHEL7 actually has it anyway, so it's a future problem, but one we should head off sooner rather than later.

**Comment by stdweird** [comment]
@ned21 you can already install it on el7. 
from the documentation, if you manage `/etc/resolv.conf`, systemd-resolv only uses it as a configuration source. and only if you modify nssswitch, systemd-resolved is actually used by glibc.

**Comment by ned21** [comment]
Thanks for confirming
