### ISSUE TITLE
ncm-metaconfig: include Singularity containers support

### ISSUE THREAD

**Issue by alvarosimon** [quattor/configuration-modules-core#953]
Singularity is a nice way to setup containers within a HPC environment:

http://singularity.lbl.gov/
http://singularity.lbl.gov/docs-hpc

It only requires to install a rpm and setup `singularity.conf` file and that could be done by  metaconfig.

**Comment by stdweird** [comment]
@jrha you should really look into this for compute work on the clusters instead of trying to get docker secured

**Comment by jrha** [comment]
Thanks, we're aware of it. Also we were never planning to run docker.
