### ISSUE TITLE
ncm-systemd 16.10-rc1: a masked service cannot be reenabled

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#962]
As of ncm-systemd 16.10.0-rc1, `masked` is considered as a service state (like `enabled` and `disabled`) when they are different things in `systemd` (an `enabled` or `started` service can be masked without impacting the enabled or started state). IMO, I think the choice made in `ncm-systemd` is good: in particular if you defined the `state` to `masked` and `startstop` to `true`,  the service is stopped and disabled in addition to be masked. The problem is that to unmask a masked service, the only possibility in `ncm-systemd` is to define its state to `enabled`. But `systemctl` doesn't allow to enable a masked service   (it does allow to disable it). 

If we want to keep the current `ncm-systemd` behaviour where we consider `masked` as a state, setting the `state` to `enabled` should unmask the service if necessary. Currently, the only way to reeanble the service requires to execute ("manually") `systemctl unmask` on the machine.

**Comment by stdweird** [comment]
masked is a state because even if you can enable/disable a masked unit, it won't make any difference.
i'll reinvestigate what needs to happen wrt transistioning from masked to enabled/disabled. there's a caveat here, in the sense that it's not always possible to change back from a masked unit.
