### ISSUE TITLE
ncm-download: can leave partial files

### ISSUE THREAD

**Issue by ajf8** [quattor/configuration-modules-core#975]
I'm looking to an issue we encountered involving ncm-download. It appears that a rather important file which we fetch with ncm-download did not download successfully, and a partial file was left. Although ncm-download reported the error, another process came along and blindly made use of the file, resulting in bad things happening.

While we will probably improve the process which consumes that file, it seems like some protection in ncm-download would be useful too, and I thought perhaps we could discuss that here before I send a pull request.

As we are using it currently, curl truncates the file it is writing to if it already exists, so I guess this could be problem if a process tries to use the file while a successful download is taking place, also.

How about downloading .$filename.part (or some other variant... should this be configurable?) in the same directory, and doing rename()? Similar to a web browser.

I thought about using the tempdir we use for kerberos credentials currently, but then it may have to move() across filesystems.

Should this be configurable and what should the default be?

**Comment by jrha** [comment]
I like the approach of `.part` files, my only concern would be with applications that consume files from `thingy.d` directories and whether these would be included in some nasty glob performed by the application.

**Comment by stdweird** [comment]
can be solved with a tempfile starting with a a '.'
similar to new filewriter, also curl downloads should be atomic.
better yet, lets use lwp+filewriter instead of curl 😄 
is there a way to determine from eg exitcode or stdout that the download with curl was incomplete?

**Comment by ajf8** [comment]
First attempt, tested and seems to work: https://github.com/quattor/configuration-modules-core/pull/976

I thought about that too, agreed I think a dotfile and a part extension should be OK (this is what I've done). It is a fairly common pattern. Things get more complicated if you try to download to another directory. 

curl will exit with a failure code if it is able to detect the download was incomplete. I suppose this depends mainly on if the server sent a Content-Length header and how the TCP connection was closed, so there's no absolute guarantee and this is why we will probably add checksum tests on the thing that consumes the file.

Currently we report failed downloads as a component error, but the file gets left behind. Using a temporary file, this can be deleted on failure, without breaking a valid (depends on the use case I suppose, outdated would be OK in ours) copy of the file.

**Comment by stdweird** [comment]
@ajf8 👍
