### ISSUE TITLE
ncm-download: part download not atomic

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#991]
this is the output of ncm-download. before the rename, the destination is deleted; which is not atomic (and not needed; rename will overwrite).
```
[DEBUG] We seem to have sucessfully retrieved a new copy of the file /some/file to /some/.file.part
[DEBUG] cleanup: noaction is false
[VERB] Cleanup unlink removed /some/file: 1
[DEBUG] move: noaction is false
[VERB] Moved /etc/.hosts.part to /some/file: 1
[DEBUG] Moved src /etc/.hosts.part to dest /some/file
[DEBUG] Succesfully renamed temporary file /some/.file.part to /some/file
```

**Comment by stdweird** [comment]
This looks like a bug in `CAF::Path`

**Comment by stdweird** [comment]
@ned21 @ajf8 is this blocking for 16.12. i'll try to find time for a fix in `CAF::Path`; possibly changing the `move` call into something else or by passing an option or so.

**Comment by ajf8** [comment]
I wouldn't say it's blocking, since it wasn't atomic before, it's just not atomic in a different way now :)

Internally we are running a slightly modified version which does not use CAF::Path, because some hosts don't have a new enough version, so it isn't a concern for us.
